import type { ComponentType } from "react";
import type { ExploreState } from "@/pages/explore/ExploreFlow";
import PatientAccessCalc from "@/components/explore/drivers/PatientAccessCalc";
import LwbsRecoveryCalc from "@/components/explore/drivers/LwbsRecoveryCalc";
import AdmissionCaptureCalc from "@/components/explore/drivers/AdmissionCaptureCalc";
import ProviderWellbeingCalc from "@/components/explore/drivers/ProviderWellbeingCalc";
import PhysicianLocumAgencyCalc from "@/components/explore/drivers/PhysicianLocumAgencyCalc";
import NursingRetentionCalc from "@/components/explore/drivers/NursingRetentionCalc";
import NursingAgencyCalc from "@/components/explore/drivers/NursingAgencyCalc";
import NursingOvertimeCalc from "@/components/explore/drivers/NursingOvertimeCalc";
import NursingHapiCalc from "@/components/explore/drivers/NursingHapiCalc";
import NursingFallsCalc from "@/components/explore/drivers/NursingFallsCalc";
import NursingCautiCalc from "@/components/explore/drivers/NursingCautiCalc";
import NursingClabsiCalc from "@/components/explore/drivers/NursingClabsiCalc";
import NursingSepsisCalc from "@/components/explore/drivers/NursingSepsisCalc";
import WrvuCalc from "@/components/explore/drivers/WrvuCalc";
import HccCaptureCalc from "@/components/explore/drivers/HccCaptureCalc";
import DenialPreventionCalc from "@/components/explore/drivers/DenialPreventionCalc";
import DrgAccuracyCalc from "@/components/explore/drivers/DrgAccuracyCalc";
import CdiQueryReductionCalc from "@/components/explore/drivers/CdiQueryReductionCalc";
import ObsDefenseCalc from "@/components/explore/drivers/ObsDefenseCalc";

export type ExploreQuadrant = 'Capacity' | 'Workforce' | 'Revenue' | 'Quality';

export type DriverScaleAxis = 'providers' | 'encounters' | 'patientDays' | 'fixed';
export type ExploreSetting = 'outpatient' | 'ed' | 'inpatient' | 'nursing';
export type ExploreDriverVisibility = 'quantified' | 'qualitative';

export interface ExploreCalcComponentProps {
  state: ExploreState;
  updateTimeDriverInputs: (updates: Partial<ExploreState['timeDriverInputs']>) => void;
  updateDocQualityInputs: (updates: Partial<ExploreState['docQualityInputs']>) => void;
  totalHoursSaved: number;
}

export interface ExploreDriverMeasureDefaults {
  deltaLabel: string;
  deltaUnit: string;
  valuePerUnitLabel: string;
  valuePerUnitDefault: number;
  valuePerUnitPrefix?: string;
  valuePerUnitSuffix?: string;
  realizationDefault: number;
  scaleAxis: DriverScaleAxis;
}

export interface ExploreDriver {
  id: string;
  label: string;
  shortDescription: string;
  tagline?: string;
  quadrant: ExploreQuadrant;
  settings: ExploreSetting[];
  visibility: ExploreDriverVisibility;
  enabledStateKey: string;
  expandedStateKey?: string;
  childOfDriverId?: string;
  subGroup?: string;
  trackedMeasureIds?: string[];
  calcComponent?: ComponentType<ExploreCalcComponentProps>;
  measureDefaults?: ExploreDriverMeasureDefaults;
}

export const EXPLORE_DRIVERS: ExploreDriver[] = [
  // ───── CAPACITY ─────
  {
    id: 'patientAccess',
    label: 'Patient Access',
    shortDescription: 'Reinvest reclaimed documentation time into additional patient visits.',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'quantified',
    enabledStateKey: 'patientAccessEnabled',
    expandedStateKey: 'patientAccessExpanded',
    calcComponent: PatientAccessCalc,
    trackedMeasureIds: ['patientsPerProvider', 'visitsPerHour', 'timeInNote'],
    measureDefaults: {
      deltaLabel: 'Additional visits per year (across all providers)',
      deltaUnit: 'visits',
      valuePerUnitLabel: 'Revenue per visit',
      valuePerUnitDefault: 250,
      valuePerUnitPrefix: '$',
      realizationDefault: 80,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'lwbsRecovery',
    label: 'LWBS Recovery',
    shortDescription: 'Recover patients who would otherwise leave the ED before being seen.',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'quantified',
    enabledStateKey: 'edLwbsEnabled',
    expandedStateKey: 'edLwbsExpanded',
    calcComponent: LwbsRecoveryCalc,
    trackedMeasureIds: ['lwbsRate', 'doorToProvider'],
    measureDefaults: {
      deltaLabel: 'Patients recovered from LWBS per year',
      deltaUnit: 'patients',
      valuePerUnitLabel: 'Revenue per ED visit',
      valuePerUnitDefault: 480,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'admissionCapture',
    label: 'Admission Capture',
    shortDescription: 'Capture revenue when LWBS-recovered patients require inpatient admission.',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'quantified',
    enabledStateKey: 'edThroughputEnabled',
    expandedStateKey: 'edThroughputExpanded',
    childOfDriverId: 'lwbsRecovery',
    calcComponent: AdmissionCaptureCalc,
    measureDefaults: {
      deltaLabel: 'Admissions captured from recovered LWBS',
      deltaUnit: 'admissions',
      valuePerUnitLabel: 'Revenue per admission',
      valuePerUnitDefault: 8000,
      valuePerUnitPrefix: '$',
      realizationDefault: 40,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'bedsideTime',
    label: 'Bedside / Direct Care Time',
    shortDescription: 'Reclaimed documentation time spent in direct patient care.',
    quadrant: 'Capacity',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingCareTimeEnabled',
    expandedStateKey: 'nursingCareTimeExpanded',
    trackedMeasureIds: ['bedsideTimeRatio'],
  },
  // ───── WORKFORCE ─────
  {
    id: 'providerWellbeing',
    label: 'Provider Wellbeing',
    shortDescription: 'Documentation burden is a leading contributor to provider burnout and turnover. This driver models the avoided replacement cost when retention improves.',
    quadrant: 'Workforce',
    settings: ['outpatient', 'ed', 'inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'wellbeingEnabled',
    expandedStateKey: 'wellbeingExpanded',
    calcComponent: ProviderWellbeingCalc,
    trackedMeasureIds: ['burnoutAssessment', 'likelihoodToStay', 'workOutsideWorkEmpirical'],
    measureDefaults: {
      deltaLabel: 'Providers retained per year',
      deltaUnit: 'providers',
      valuePerUnitLabel: 'Replacement cost per provider',
      valuePerUnitDefault: 400000,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'physicianLocumAgency',
    label: 'Locum & Agency Cost Avoidance',
    shortDescription: 'Reduced reliance on contracted physician coverage as retention improves.',
    quadrant: 'Workforce',
    settings: ['outpatient', 'ed', 'inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'physicianAgencyEnabled',
    expandedStateKey: 'physicianAgencyExpanded',
    childOfDriverId: 'providerWellbeing',
    calcComponent: PhysicianLocumAgencyCalc,
    trackedMeasureIds: ['agencyLocumSpend'],
    measureDefaults: {
      deltaLabel: 'Provider-weeks of locum coverage avoided',
      deltaUnit: 'weeks',
      valuePerUnitLabel: 'Weekly locum premium',
      valuePerUnitDefault: 5000,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'nursingRetention',
    label: 'RN Retention',
    shortDescription: 'Reduced documentation burden helps retain experienced nurses. Models avoided replacement cost.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingRetentionEnabled',
    expandedStateKey: 'nursingRetentionExpanded',
    calcComponent: NursingRetentionCalc,
    trackedMeasureIds: ['rnRetention', 'burnoutAssessment', 'likelihoodToStay'],
    measureDefaults: {
      deltaLabel: 'Nurses retained per year',
      deltaUnit: 'nurses',
      valuePerUnitLabel: 'Replacement cost per nurse',
      valuePerUnitDefault: 56300,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'nursingAgency',
    label: 'Travel & Agency Cost Avoidance',
    shortDescription: 'Reduced reliance on travel/agency nurses as retention stabilizes.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingAgencyEnabled',
    expandedStateKey: 'nursingAgencyExpanded',
    childOfDriverId: 'nursingRetention',
    calcComponent: NursingAgencyCalc,
    trackedMeasureIds: ['travelAgencyNurseSpend'],
    measureDefaults: {
      deltaLabel: 'Nurse-weeks of agency coverage avoided',
      deltaUnit: 'weeks',
      valuePerUnitLabel: 'Weekly agency premium',
      valuePerUnitDefault: 2500,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'nursingOvertime',
    label: 'Overtime Reduction',
    shortDescription: 'Faster charting reduces documentation-related overtime hours.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingOtEnabled',
    expandedStateKey: 'nursingOtExpanded',
    calcComponent: NursingOvertimeCalc,
    trackedMeasureIds: ['documentationOvertime', 'chartingAfterShift'],
    measureDefaults: {
      deltaLabel: 'Overtime hours eliminated per year',
      deltaUnit: 'hours',
      valuePerUnitLabel: 'Overtime hourly rate',
      valuePerUnitDefault: 75,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  // ───── QUALITY ─────
  // Outpatient (qualitative — trimmed by R-IA-3 to 3 drivers)
  {
    id: 'opCareContinuity',
    label: 'Care Continuity',
    shortDescription: 'Better-documented handoffs improve continuity across encounters and providers.',
    tagline: 'Continuity of care across encounters and providers',
    quadrant: 'Quality',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opCareContinuityEnabled',
    expandedStateKey: 'opCareContinuityExpanded',
  },
  {
    id: 'opNoteStarRating',
    label: 'Note Quality (Star Rating)',
    shortDescription: 'Internal note-quality scores improve with structured AI drafting.',
    tagline: 'Internal note-quality scores, outpatient setting',
    quadrant: 'Quality',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opNoteStarRatingEnabled',
    expandedStateKey: 'opNoteStarRatingExpanded',
  },
  {
    id: 'opDiagnosisCapture',
    label: 'Diagnosis Capture',
    shortDescription: 'More complete capture of conditions discussed during the visit.',
    tagline: 'Conditions discussed during the visit captured in documentation',
    quadrant: 'Quality',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opDiagnosisCaptureEnabled',
    expandedStateKey: 'opDiagnosisCaptureExpanded',
  },
  // ED Quality (qualitative — 3 drivers; R-ED-1: Provider Communication → Admission Hand-Off Completeness)
  {
    id: 'edNoteStarRating',
    label: 'ED Note Quality (Star Rating)',
    shortDescription: 'Internal note-quality scores improve in the ED with structured AI drafting.',
    tagline: 'Internal note-quality scores, ED setting',
    quadrant: 'Quality',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edNoteStarRatingEnabled',
    expandedStateKey: 'edNoteStarRatingExpanded',
  },
  {
    id: 'edPressGaney',
    label: 'Patient Experience (Press Ganey)',
    shortDescription: 'More attentive face-time during the encounter lifts patient experience scores.',
    tagline: 'Patient experience scores tied to face-time during the encounter',
    quadrant: 'Quality',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edPressGaneyEnabled',
    expandedStateKey: 'edPressGaneyExpanded',
  },
  {
    id: 'edAdmissionHandoff',
    label: 'Admission Hand-Off Completeness',
    shortDescription: 'Share of ED-to-inpatient hand-offs with complete documentation at admission. When the ED admits, downstream inpatient teams inherit the quality of the ED note.',
    tagline: 'Complete documentation at ED-to-inpatient transitions',
    quadrant: 'Quality',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edAdmissionHandoffEnabled',
    expandedStateKey: 'edAdmissionHandoffExpanded',
    trackedMeasureIds: [],
  },
  // IP (qualitative)
  {
    id: 'ipNoteStarRating',
    label: 'IP Note Quality (Star Rating)',
    shortDescription: 'Internal note-quality scores improve in the inpatient setting.',
    tagline: 'Internal note-quality scores, inpatient setting',
    quadrant: 'Quality',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipNoteStarRatingEnabled',
    expandedStateKey: 'ipNoteStarRatingExpanded',
  },
  // Nursing (5 quantified + 2 qualitative)
  {
    id: 'nursingHapi',
    label: 'HAPI Prevention',
    shortDescription: 'Real-time skin and turning documentation prevents hospital-acquired pressure injuries.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingHapiEnabled',
    expandedStateKey: 'nursingHapiExpanded',
    subGroup: 'Harm Events',
    calcComponent: NursingHapiCalc,
    measureDefaults: {
      deltaLabel: 'HAPIs prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per HAPI',
      valuePerUnitDefault: 25000,
      valuePerUnitPrefix: '$',
      realizationDefault: 85,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingFalls',
    label: 'Falls Prevention',
    shortDescription: 'Real-time risk assessments and Morse score updates reduce inpatient falls.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingFallsEnabled',
    expandedStateKey: 'nursingFallsExpanded',
    subGroup: 'Harm Events',
    calcComponent: NursingFallsCalc,
    measureDefaults: {
      deltaLabel: 'Falls prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per fall',
      valuePerUnitDefault: 6500,
      valuePerUnitPrefix: '$',
      realizationDefault: 85,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingCauti',
    label: 'CAUTI Prevention',
    shortDescription: 'Daily catheter-necessity documentation supports earlier removal and bundle adherence.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingCautiEnabled',
    expandedStateKey: 'nursingCautiExpanded',
    subGroup: 'Bundle Compliance',
    calcComponent: NursingCautiCalc,
    measureDefaults: {
      deltaLabel: 'CAUTIs prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per CAUTI',
      valuePerUnitDefault: 13000,
      valuePerUnitPrefix: '$',
      realizationDefault: 80,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingClabsi',
    label: 'CLABSI Prevention',
    shortDescription: 'Bundle compliance and timely line documentation reduce central line bloodstream infections.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingClabsiEnabled',
    expandedStateKey: 'nursingClabsiExpanded',
    subGroup: 'Bundle Compliance',
    calcComponent: NursingClabsiCalc,
    measureDefaults: {
      deltaLabel: 'CLABSIs prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per CLABSI',
      valuePerUnitDefault: 20000,
      valuePerUnitPrefix: '$',
      realizationDefault: 80,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingSepsis',
    label: 'Sepsis Bundle Compliance',
    shortDescription: 'Time-stamped vitals and antibiotic documentation lift SEP-1 bundle compliance.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingSepsisEnabled',
    expandedStateKey: 'nursingSepsisExpanded',
    subGroup: 'Bundle Compliance',
    calcComponent: NursingSepsisCalc,
    measureDefaults: {
      deltaLabel: 'Sepsis bundle non-compliance cases avoided',
      deltaUnit: 'cases',
      valuePerUnitLabel: 'Excess cost per case',
      valuePerUnitDefault: 3500,
      valuePerUnitPrefix: '$',
      realizationDefault: 60,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingHcahps',
    label: 'HCAHPS (Nurse Communication)',
    shortDescription: 'More bedside time supports nurse-communication composite gains.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingHcahpsEnabled',
    expandedStateKey: 'nursingHcahpsExpanded',
  },
  {
    id: 'nursingMedError',
    label: 'Medication Error Reduction',
    shortDescription: 'Cleaner real-time documentation reduces medication-related near misses and errors.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingMedErrorEnabled',
    expandedStateKey: 'nursingMedErrorExpanded',
  },

  // ───── REVENUE ─────
  {
    id: 'wrvu',
    label: 'wRVU Capture',
    shortDescription: 'When notes fully reflect visit complexity, E/M levels often code higher.',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'quantified',
    enabledStateKey: 'wrvuEnabled',
    expandedStateKey: 'wrvuExpanded',
    calcComponent: WrvuCalc,
    trackedMeasureIds: ['wrvu'],
    measureDefaults: {
      deltaLabel: 'wRVU lift per visit',
      deltaUnit: 'wRVU',
      valuePerUnitLabel: 'Conversion factor',
      valuePerUnitDefault: 50,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'edEmLevel',
    label: 'E&M Level Accuracy',
    shortDescription: 'Capture the true complexity of ED visits supporting accurate E/M leveling.',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'quantified',
    enabledStateKey: 'wrvuEnabled',
    expandedStateKey: 'wrvuExpanded',
    calcComponent: WrvuCalc,
    trackedMeasureIds: ['wrvuPerShift', 'emLevel'],
    measureDefaults: {
      deltaLabel: 'E/M wRVU lift per visit',
      deltaUnit: 'wRVU',
      valuePerUnitLabel: 'Conversion factor',
      valuePerUnitDefault: 50,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'hccCapture',
    label: 'HCC Capture',
    shortDescription: 'Recapture missed diagnoses for the Medicare Advantage population.',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'quantified',
    enabledStateKey: 'hccEnabled',
    expandedStateKey: 'hccExpanded',
    calcComponent: HccCaptureCalc,
    trackedMeasureIds: ['hccCapture'],
    measureDefaults: {
      deltaLabel: 'HCCs documented',
      deltaUnit: 'HCCs',
      valuePerUnitLabel: 'Value per HCC',
      valuePerUnitDefault: 1500,
      valuePerUnitPrefix: '$',
      realizationDefault: 40,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'denialPrevention',
    label: 'Denial Prevention',
    shortDescription: 'Reduce documentation-related claim denials.',
    quadrant: 'Revenue',
    settings: ['outpatient', 'ed'],
    visibility: 'quantified',
    enabledStateKey: 'denialsEnabled',
    expandedStateKey: 'denialsExpanded',
    calcComponent: DenialPreventionCalc,
    trackedMeasureIds: ['cleanClaim', 'medicalNecessityDenial'],
    measureDefaults: {
      deltaLabel: 'Denials prevented',
      deltaUnit: 'claims',
      valuePerUnitLabel: 'Avg claim value',
      valuePerUnitDefault: 500,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'drgAccuracy',
    label: 'DRG Accuracy',
    shortDescription: 'Capture clinical complexity discussed during care that affects DRG assignment.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'ipDrgEnabled',
    expandedStateKey: 'ipDrgExpanded',
    calcComponent: DrgAccuracyCalc,
    trackedMeasureIds: ['drgAccuracy', 'ccMccCapture', 'caseMixIndex'],
    measureDefaults: {
      deltaLabel: 'Admissions with DRG lift',
      deltaUnit: 'admissions',
      valuePerUnitLabel: 'Avg DRG payment lift',
      valuePerUnitDefault: 4000,
      valuePerUnitPrefix: '$',
      realizationDefault: 33,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'cdiQueryReduction',
    label: 'CDI Query Reduction',
    shortDescription: 'Fewer queries when documentation is complete upfront.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'ipCdiEnabled',
    expandedStateKey: 'ipCdiExpanded',
    calcComponent: CdiQueryReductionCalc,
    trackedMeasureIds: ['cdiQueryReduction'],
    measureDefaults: {
      deltaLabel: 'Queries avoided',
      deltaUnit: 'queries',
      valuePerUnitLabel: 'Cost per query',
      valuePerUnitDefault: 50,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'obsDefense',
    label: 'Observation / IP Status Defense',
    shortDescription: 'Defensible documentation supporting admission status determinations.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'ipObsDefenseEnabled',
    expandedStateKey: 'ipObsDefenseExpanded',
    calcComponent: ObsDefenseCalc,
    trackedMeasureIds: ['medicalNecessityDenial'],
    measureDefaults: {
      deltaLabel: 'Appeal-defensible denials',
      deltaUnit: 'claims',
      valuePerUnitLabel: 'Avg contested claim value',
      valuePerUnitDefault: 10000,
      valuePerUnitPrefix: '$',
      realizationDefault: 25,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'nursingCdiResponse',
    label: 'CDI Query Response',
    shortDescription: 'Faster, more complete nursing documentation supports DRG accuracy and timeliness.',
    quadrant: 'Revenue',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingCdiResponseEnabled',
    expandedStateKey: 'nursingCdiResponseExpanded',
    trackedMeasureIds: ['cdiQueryResponseRate'],
  },
  {
    id: 'nursingDocCompletion',
    label: 'Documentation Completion',
    shortDescription: 'Timely nursing documentation reduces billing delays and discharge holds.',
    quadrant: 'Revenue',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingDocCompletionEnabled',
    expandedStateKey: 'nursingDocCompletionExpanded',
    trackedMeasureIds: ['nursingDocCompletion'],
  },

  // ───── R-IA-2 / R-IA-3 — Curated qualitative drivers (toggleable, no $ math) ─────
  // OP Capacity (qualitative — 3 drivers, R-IA-3 trim)
  {
    id: 'opThirdNextAvailable',
    label: '3rd Next Available',
    shortDescription: 'Days until the third next available appointment slot. A standard access metric.',
    tagline: 'Days until the third next available appointment',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opThirdNextAvailableEnabled',
    expandedStateKey: 'opThirdNextAvailableExpanded',
    trackedMeasureIds: ['thirdNextAvailable'],
  },
  {
    id: 'opSameDayAccess',
    label: 'Same-Day or Urgent Access Slots',
    shortDescription: 'Number of same-day or urgent slots opened on the schedule. A measure of access for patients who need to be seen quickly.',
    tagline: 'Same-day and urgent slots opened on the schedule',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opSameDayAccessEnabled',
    expandedStateKey: 'opSameDayAccessExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'opExtendedVisitTime',
    label: 'Extended Visit Time for Complex Patients',
    shortDescription: 'Average minutes spent with complex patients during their visit. Tracks whether reclaimed time is reinvested in deeper care for harder cases.',
    tagline: 'Time with complex patients — where reclaimed time goes',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opExtendedVisitTimeEnabled',
    expandedStateKey: 'opExtendedVisitTimeExpanded',
    trackedMeasureIds: [],
  },

  // OP Workforce (qualitative — 3 drivers, R-IA-3 trim; Burnout Score listed last)
  {
    id: 'opAfterHoursDoc',
    label: 'After-Hours Documentation',
    shortDescription: 'Time providers spend in the EHR outside scheduled clinical hours. A widely used signal for documentation burden.',
    tagline: 'EHR time logged outside scheduled clinical hours',
    quadrant: 'Workforce',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opAfterHoursDocEnabled',
    expandedStateKey: 'opAfterHoursDocExpanded',
    trackedMeasureIds: ['workOutsideWorkEmpirical'],
  },
  {
    id: 'opNotesBeforeLeaving',
    label: 'Notes Completed Before Leaving the Clinic',
    shortDescription: 'Share of encounter notes signed before the provider leaves the clinic that day. Tracks the shift away from after-hours charting.',
    tagline: 'Notes signed before leaving the clinic that day',
    quadrant: 'Workforce',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opNotesBeforeLeavingEnabled',
    expandedStateKey: 'opNotesBeforeLeavingExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'opBurnoutTracking',
    label: 'Burnout Score',
    shortDescription: 'Score from a validated burnout instrument (e.g., Maslach Burnout Inventory). Tracked as a leading indicator for retention.',
    tagline: 'Validated burnout score — leading indicator for retention',
    quadrant: 'Workforce',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opBurnoutTrackingEnabled',
    expandedStateKey: 'opBurnoutTrackingExpanded',
    trackedMeasureIds: ['burnoutAssessment'],
  },

  // OP Revenue (qualitative — 3 drivers, R-IA-3 trim — all new)
  {
    id: 'opEmLevelDistribution',
    label: 'E&M Level Distribution Shift',
    shortDescription: 'Distribution of E/M codes assigned across encounters. A shift toward higher-level codes can indicate documentation more fully reflects visit complexity.',
    tagline: 'Distribution of E/M codes across encounters',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opEmLevelDistributionEnabled',
    expandedStateKey: 'opEmLevelDistributionExpanded',
    trackedMeasureIds: ['emLevel'],
  },
  {
    id: 'opCdiQueryTrend',
    label: 'CDI Query Volume Trend',
    shortDescription: 'Volume of CDI queries returned to providers post-visit. Decreasing query volume often signals more complete documentation at the point of care.',
    tagline: 'CDI query volume post-visit — falling signals better docs',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opCdiQueryTrendEnabled',
    expandedStateKey: 'opCdiQueryTrendExpanded',
    trackedMeasureIds: ['opCdiQueryReduction'],
  },
  {
    id: 'opCodingSpecificity',
    label: 'Coding Specificity Improvement',
    shortDescription: 'Share of diagnoses coded to the highest available ICD-10 specificity. Tracked as a downstream signal of clinical detail captured in notes.',
    tagline: 'Diagnoses coded to highest ICD-10 specificity',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opCodingSpecificityEnabled',
    expandedStateKey: 'opCodingSpecificityExpanded',
    trackedMeasureIds: ['diagnosisSpecificity'],
  },

  // ED Capacity (qualitative — 3 drivers; R-ED-1: Door-to-Disposition + Bed Turnover replaced for product reality)
  {
    id: 'edDoorToProvider',
    label: 'Door-to-Provider Time',
    shortDescription: 'Minutes from patient arrival to first provider contact. An upstream indicator for LWBS and patient experience; faster note-write frees clinicians to see the next patient sooner.',
    tagline: 'Minutes from patient arrival to first provider contact',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edDoorToProviderEnabled',
    expandedStateKey: 'edDoorToProviderExpanded',
    trackedMeasureIds: ['doorToProvider'],
  },
  {
    id: 'edEncountersPerShift',
    label: 'Encounters per Provider per Shift',
    shortDescription: 'Average patient volume per provider per shift. Direct throughput proof — faster documentation makes more capacity per shift available.',
    tagline: 'Average patients seen per provider per shift',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edEncountersPerShiftEnabled',
    expandedStateKey: 'edEncountersPerShiftExpanded',
    trackedMeasureIds: ['patientsPerShift'],
  },
  {
    id: 'edEndOfShiftCompletion',
    label: 'End-of-Shift Note Completion Rate',
    shortDescription: 'Share of encounter notes signed before the provider leaves the shift. Tracks the shift away from end-of-shift batch charting.',
    tagline: 'Notes signed before the provider leaves the shift',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edEndOfShiftCompletionEnabled',
    expandedStateKey: 'edEndOfShiftCompletionExpanded',
    trackedMeasureIds: [],
  },

  // ED Workforce (qualitative — 3 drivers, expanded by R-IA-4)
  {
    id: 'edAfterHoursDoc',
    label: 'After-Hours Documentation',
    shortDescription: 'Time providers spend in the EHR outside scheduled shift hours. A widely used signal for documentation burden in shift-based settings.',
    tagline: 'EHR time logged outside scheduled shift hours',
    quadrant: 'Workforce',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edAfterHoursDocEnabled',
    expandedStateKey: 'edAfterHoursDocExpanded',
    trackedMeasureIds: ['workOutsideWorkEmpirical'],
  },
  {
    id: 'edBurnoutTracking',
    label: 'Burnout Score',
    shortDescription: 'Score from a validated burnout instrument. Tracked as a leading indicator for retention.',
    tagline: 'Validated burnout score — leading indicator for retention',
    quadrant: 'Workforce',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edBurnoutTrackingEnabled',
    expandedStateKey: 'edBurnoutTrackingExpanded',
    trackedMeasureIds: ['burnoutAssessment'],
  },
  {
    id: 'edLikelihoodToStay',
    label: 'Likelihood to Stay',
    shortDescription: 'Survey item measuring intent to remain in current role over a defined timeframe.',
    tagline: 'Intent to remain in current role, surveyed',
    quadrant: 'Workforce',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edLikelihoodToStayEnabled',
    expandedStateKey: 'edLikelihoodToStayExpanded',
    trackedMeasureIds: ['likelihoodToStay'],
  },

  // ED Revenue (qualitative — 3 drivers; R-ED-1: CDI Query Volume Trend → Down-coding Rate)
  {
    id: 'edCleanClaim',
    label: 'Clean Claim Rate',
    shortDescription: 'Share of ED claims accepted on first submission. Tracked as a downstream signal of documentation completeness.',
    tagline: 'Claims accepted on first submission',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edCleanClaimEnabled',
    expandedStateKey: 'edCleanClaimExpanded',
    trackedMeasureIds: ['cleanClaim'],
  },
  {
    id: 'edEmLevelDistribution',
    label: 'E&M Level Distribution Shift',
    shortDescription: 'Distribution of ED E/M codes (99281-99285) across encounters. A shift toward higher-level codes can indicate documentation more fully reflects visit complexity.',
    tagline: 'Distribution of ED E/M codes across encounters',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edEmLevelDistributionEnabled',
    expandedStateKey: 'edEmLevelDistributionExpanded',
    trackedMeasureIds: ['emLevel'],
  },
  {
    id: 'edDowncodingRate',
    label: 'Down-coding Rate',
    shortDescription: 'Share of claims down-coded by payers (e.g., 99284 → 99283) due to insufficient documentation. Decreasing rate signals stronger documentation supporting the billed level.',
    tagline: 'Claims down-coded by payers due to insufficient documentation',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edDowncodingRateEnabled',
    expandedStateKey: 'edDowncodingRateExpanded',
    trackedMeasureIds: [],
  },

  // IP Capacity (qualitative — 3 drivers, restructured by R-IA-5; ALOS removed)
  // (R-IP-1: roundingEfficiency removed; ipHnpCompletion24h is appended at end of array and now renders FIRST in IP Capacity.)
  {
    id: 'ipDocumentationLag',
    label: 'Documentation Lag',
    shortDescription: 'Hours from clinical event to signed note. Faster documentation makes current information available to consulting physicians, care managers, and discharge planners — capacity follows information flow.',
    tagline: 'Time from clinical event to signed note',
    quadrant: 'Capacity',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipDocumentationLagEnabled',
    expandedStateKey: 'ipDocumentationLagExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'ipDischargeSummaryTime',
    label: 'Discharge Summary Completion Time',
    shortDescription: 'Hours from discharge order to signed discharge summary. Bed turnover and downstream care transitions depend on completed documentation.',
    tagline: 'Hours from discharge order to signed summary',
    quadrant: 'Capacity',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipDischargeSummaryTimeEnabled',
    expandedStateKey: 'ipDischargeSummaryTimeExpanded',
    trackedMeasureIds: [],
  },

  // IP Workforce (qualitative — 3 drivers, restructured by R-IA-5; Likelihood to Stay removed)
  {
    id: 'ipAfterHoursDoc',
    label: 'After-Hours Documentation',
    shortDescription: 'Time hospitalists spend in the EHR outside scheduled shift hours. A widely used signal for documentation burden in hospital medicine.',
    tagline: 'EHR time logged outside scheduled shift hours',
    quadrant: 'Workforce',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipAfterHoursDocEnabled',
    expandedStateKey: 'ipAfterHoursDocExpanded',
    trackedMeasureIds: ['workOutsideWorkEmpirical'],
  },
  {
    id: 'ipBurnoutTracking',
    label: 'Burnout Score',
    shortDescription: 'Score from a validated burnout instrument. Tracked as a leading indicator for hospitalist retention.',
    tagline: 'Validated burnout score — leading indicator for retention',
    quadrant: 'Workforce',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipBurnoutTrackingEnabled',
    expandedStateKey: 'ipBurnoutTrackingExpanded',
    trackedMeasureIds: ['burnoutAssessment'],
  },
  {
    id: 'ipTimeToSignNote',
    label: 'Time to Sign Note',
    shortDescription: 'Hours from encounter completion to signed note. Hospitalists have a CMS 24-hour H&P signature requirement; this metric tracks compliance and workflow burden.',
    tagline: 'Hours from encounter end to signed note',
    quadrant: 'Workforce',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipTimeToSignNoteEnabled',
    expandedStateKey: 'ipTimeToSignNoteExpanded',
    trackedMeasureIds: [],
  },

  // IP Revenue (qualitative — 3 drivers, expanded by R-IA-5)
  {
    id: 'ipCmiTracking',
    label: 'Case Mix Index',
    shortDescription: 'Weighted average of DRG relative weights. Tracked as a downstream signal of CC/MCC capture and DRG accuracy.',
    tagline: 'Downstream signal of CC/MCC capture and DRG accuracy',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipCmiTrackingEnabled',
    expandedStateKey: 'ipCmiTrackingExpanded',
    trackedMeasureIds: ['caseMixIndex'],
  },
  {
    id: 'ipCcMccCapture',
    label: 'CC/MCC Capture Trend',
    shortDescription: 'Trend in complication / major-complication capture rate across admissions. CC and MCC documentation drives DRG weighting and inpatient reimbursement.',
    tagline: 'Complication and major-complication capture rate trend',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipCcMccCaptureEnabled',
    expandedStateKey: 'ipCcMccCaptureExpanded',
    trackedMeasureIds: ['ccMccCapture'],
  },
  {
    id: 'ipCdiQueryTrend',
    label: 'CDI Query Volume Trend',
    shortDescription: 'Volume of CDI queries returned to providers per admission. Decreasing query volume often signals more complete documentation at the point of care.',
    tagline: 'Query volume per admission — falling signals better upfront docs',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipCdiQueryTrendEnabled',
    expandedStateKey: 'ipCdiQueryTrendExpanded',
    trackedMeasureIds: [],
  },

  // Nursing Workforce (qualitative — 3 drivers, expanded by R-IA-6)
  {
    id: 'nursingLikelihoodToStay',
    label: 'Likelihood to Stay',
    shortDescription: 'Survey item measuring intent to remain in current role over a defined timeframe.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingLikelihoodToStayEnabled',
    expandedStateKey: 'nursingLikelihoodToStayExpanded',
    trackedMeasureIds: ['likelihoodToStay'],
  },

  // Nursing Capacity (qualitative — added by R-IA-6; bedsideTime renders FIRST from earlier in the array)
  {
    id: 'nursingDocumentationLag',
    label: 'Documentation Lag',
    shortDescription: 'Minutes from a care event to when it appears in the chart. Faster documentation makes patient information available to the next shift, the charge nurse, and the care team without waiting for end-of-shift batch entry.',
    quadrant: 'Capacity',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingDocumentationLagEnabled',
    expandedStateKey: 'nursingDocumentationLagExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'nursingPointOfCareDoc',
    label: 'Point-of-Care Documentation Rate',
    shortDescription: 'Share of nursing documentation completed at the moment of care versus batched at the end of shift. The defining shift ambient nursing documentation enables.',
    quadrant: 'Capacity',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingPointOfCareDocEnabled',
    expandedStateKey: 'nursingPointOfCareDocExpanded',
    trackedMeasureIds: [],
  },

  // Nursing Workforce (qualitative — added by R-IA-6)
  {
    id: 'nursingBurnout',
    label: 'Burnout Score',
    shortDescription: 'Score from a validated burnout instrument (e.g., Maslach Burnout Inventory) administered to nursing staff. Tracked as a leading indicator for retention.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingBurnoutEnabled',
    expandedStateKey: 'nursingBurnoutExpanded',
    trackedMeasureIds: ['burnoutAssessment'],
  },
  {
    id: 'nursingChartingAfterShift',
    label: 'Charting After Shift',
    shortDescription: 'Minutes nurses spend in the EHR after their scheduled shift ends. A direct burden signal — and the lever that ambient nursing documentation reduces.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingChartingAfterShiftEnabled',
    expandedStateKey: 'nursingChartingAfterShiftExpanded',
    trackedMeasureIds: ['chartingAfterShift'],
  },
  // ───── R-IP-1: IP Capacity (replaces roundingEfficiency) ─────
  {
    id: 'ipHnpCompletion24h',
    label: 'H&P Completion Within 24 Hours',
    shortDescription: 'Share of inpatient admissions with the H&P note signed within the CMS-required 24-hour window. A direct compliance and capacity signal — late H&Ps delay care plans, consults, and downstream actions.',
    tagline: 'H&P signed within the CMS-required 24-hour window',
    quadrant: 'Capacity',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipHnpCompletion24hEnabled',
    expandedStateKey: 'ipHnpCompletion24hExpanded',
    trackedMeasureIds: [],
  },
  // ───── R-IP-1: IP Quality (replaces HCAHPS Composite + 30-Day Readmission) ─────
  {
    id: 'ipHandoffCompleteness',
    label: 'Hand-Off Completeness',
    shortDescription: 'Share of provider hand-offs (shift-change, consult, transfer) with complete documentation at time of transition. Faster, more complete progress notes feed cleaner hand-offs.',
    tagline: 'Complete documentation at shift change and consult transitions',
    quadrant: 'Quality',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipHandoffCompletenessEnabled',
    expandedStateKey: 'ipHandoffCompletenessExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'ipDischargeDocCompleteness',
    label: 'Discharge Documentation Completeness',
    shortDescription: 'Share of discharges with complete summary documentation supporting post-acute care, payer review, and readmission risk reduction.',
    tagline: 'Complete discharge summaries supporting post-acute care',
    quadrant: 'Quality',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipDischargeDocCompletenessEnabled',
    expandedStateKey: 'ipDischargeDocCompletenessExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'ipLeapfrog',
    label: 'Leapfrog Hospital Safety Grade',
    shortDescription: 'Composite hospital safety grade from The Leapfrog Group. Tracked as a quality posture indicator; documentation completeness is one of several inputs.',
    tagline: 'Composite hospital safety grade — documentation is one input',
    quadrant: 'Quality',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipLeapfrogEnabled',
    expandedStateKey: 'ipLeapfrogExpanded',
    trackedMeasureIds: [],
  },
];

export function getDriversForPage(quadrant: ExploreQuadrant, setting: ExploreSetting): ExploreDriver[] {
  return EXPLORE_DRIVERS.filter(d => d.quadrant === quadrant && d.settings.includes(setting));
}

export function isDriverEnabled(driver: ExploreDriver, state: ExploreState): boolean {
  const td = state.timeDriverInputs as any;
  const dq = state.docQualityInputs as any;
  return Boolean(td[driver.enabledStateKey] ?? dq[driver.enabledStateKey]);
}
