import type { ComponentType } from "react";
import type { ExploreState } from "@/pages/explore/ExploreFlow";
import PatientAccessCalc from "@/components/explore/drivers/PatientAccessCalc";
import LwbsRecoveryCalc from "@/components/explore/drivers/LwbsRecoveryCalc";
import AdmissionCaptureCalc from "@/components/explore/drivers/AdmissionCaptureCalc";
import ProviderWellbeingCalc from "@/components/explore/drivers/ProviderWellbeingCalc";
import PhysicianLocumAgencyCalc from "@/components/explore/drivers/PhysicianLocumAgencyCalc";
import NursingRetentionCalc from "@/components/explore/drivers/NursingRetentionCalc";
import NursingAgencyCalc from "@/components/explore/drivers/NursingAgencyCalc";
import NursingOvertimeCalc from "@/components/explore/drivers/NursingOvertimeCalc";
import NursingHapiCalc from "@/components/explore/drivers/NursingHapiCalc";
import NursingFallsCalc from "@/components/explore/drivers/NursingFallsCalc";
import NursingCautiCalc from "@/components/explore/drivers/NursingCautiCalc";
import NursingClabsiCalc from "@/components/explore/drivers/NursingClabsiCalc";
import NursingSepsisCalc from "@/components/explore/drivers/NursingSepsisCalc";
import WrvuCalc from "@/components/explore/drivers/WrvuCalc";
import HccCaptureCalc from "@/components/explore/drivers/HccCaptureCalc";
import DenialPreventionCalc from "@/components/explore/drivers/DenialPreventionCalc";
import DrgAccuracyCalc from "@/components/explore/drivers/DrgAccuracyCalc";
import CdiQueryReductionCalc from "@/components/explore/drivers/CdiQueryReductionCalc";
import ObsDefenseCalc from "@/components/explore/drivers/ObsDefenseCalc";
import EmCodingCalc from "@/components/explore/drivers/EmCodingCalc";

export type ExploreQuadrant = 'Capacity' | 'Workforce' | 'Revenue' | 'Quality';

export type DriverScaleAxis = 'providers' | 'encounters' | 'patientDays' | 'fixed';
export type ExploreSetting = 'outpatient' | 'ed' | 'inpatient' | 'nursing';
export type ExploreDriverVisibility = 'quantified' | 'qualitative';

export interface ExploreCalcComponentProps {
  state: ExploreState;
  updateTimeDriverInputs: (updates: Partial<ExploreState['timeDriverInputs']>) => void;
  updateDocQualityInputs: (updates: Partial<ExploreState['docQualityInputs']>) => void;
  totalHoursSaved: number;
}

export interface ExploreDriverMeasureDefaults {
  deltaLabel: string;
  deltaUnit: string;
  valuePerUnitLabel: string;
  valuePerUnitDefault: number;
  valuePerUnitPrefix?: string;
  valuePerUnitSuffix?: string;
  realizationDefault: number;
  scaleAxis: DriverScaleAxis;
}

export interface ExploreDriver {
  id: string;
  label: string;
  shortDescription: string;
  quadrant: ExploreQuadrant;
  settings: ExploreSetting[];
  visibility: ExploreDriverVisibility;
  enabledStateKey: string;
  expandedStateKey?: string;
  childOfDriverId?: string;
  trackedMeasureIds?: string[];
  calcComponent?: ComponentType<ExploreCalcComponentProps>;
  measureDefaults?: ExploreDriverMeasureDefaults;
}

export const EXPLORE_DRIVERS: ExploreDriver[] = [
  // ───── CAPACITY ─────
  {
    id: 'patientAccess',
    label: 'Patient Access',
    shortDescription: 'Reinvest reclaimed documentation time into additional patient visits.',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'quantified',
    enabledStateKey: 'patientAccessEnabled',
    expandedStateKey: 'patientAccessExpanded',
    calcComponent: PatientAccessCalc,
    trackedMeasureIds: ['patientsPerProvider', 'visitsPerHour', 'timeInNote'],
    measureDefaults: {
      deltaLabel: 'Additional visits per year (across all providers)',
      deltaUnit: 'visits',
      valuePerUnitLabel: 'Revenue per visit',
      valuePerUnitDefault: 250,
      valuePerUnitPrefix: '$',
      realizationDefault: 80,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'lwbsRecovery',
    label: 'LWBS Recovery',
    shortDescription: 'Recover patients who would otherwise leave the ED before being seen.',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'quantified',
    enabledStateKey: 'edLwbsEnabled',
    expandedStateKey: 'edLwbsExpanded',
    calcComponent: LwbsRecoveryCalc,
    trackedMeasureIds: ['lwbsRate', 'doorToProvider'],
    measureDefaults: {
      deltaLabel: 'Patients recovered from LWBS per year',
      deltaUnit: 'patients',
      valuePerUnitLabel: 'Revenue per ED visit',
      valuePerUnitDefault: 480,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'admissionCapture',
    label: 'Admission Capture',
    shortDescription: 'Capture revenue when LWBS-recovered patients require inpatient admission.',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'quantified',
    enabledStateKey: 'edThroughputEnabled',
    expandedStateKey: 'edThroughputExpanded',
    childOfDriverId: 'lwbsRecovery',
    calcComponent: AdmissionCaptureCalc,
    measureDefaults: {
      deltaLabel: 'Admissions captured from recovered LWBS',
      deltaUnit: 'admissions',
      valuePerUnitLabel: 'Revenue per admission',
      valuePerUnitDefault: 8000,
      valuePerUnitPrefix: '$',
      realizationDefault: 40,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'roundingEfficiency',
    label: 'Rounding Efficiency',
    shortDescription: 'More time at the bedside during rounds rather than in the EHR.',
    quadrant: 'Capacity',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipRoundingEnabled',
    expandedStateKey: 'ipRoundingExpanded',
  },
  {
    id: 'bedsideTime',
    label: 'Bedside / Direct Care Time',
    shortDescription: 'Reclaimed documentation time spent in direct patient care.',
    quadrant: 'Capacity',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingCareTimeEnabled',
    expandedStateKey: 'nursingCareTimeExpanded',
    trackedMeasureIds: ['bedsideTimeRatio'],
  },
  // ───── WORKFORCE ─────
  {
    id: 'providerWellbeing',
    label: 'Provider Wellbeing',
    shortDescription: 'Documentation burden is a leading contributor to provider burnout and turnover. This driver models the avoided replacement cost when retention improves.',
    quadrant: 'Workforce',
    settings: ['outpatient', 'ed', 'inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'wellbeingEnabled',
    expandedStateKey: 'wellbeingExpanded',
    calcComponent: ProviderWellbeingCalc,
    trackedMeasureIds: ['burnoutAssessment', 'likelihoodToStay', 'workOutsideWorkEmpirical'],
    measureDefaults: {
      deltaLabel: 'Providers retained per year',
      deltaUnit: 'providers',
      valuePerUnitLabel: 'Replacement cost per provider',
      valuePerUnitDefault: 400000,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'physicianLocumAgency',
    label: 'Locum & Agency Cost Avoidance',
    shortDescription: 'Reduced reliance on contracted physician coverage as retention improves.',
    quadrant: 'Workforce',
    settings: ['outpatient', 'ed', 'inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'physicianAgencyEnabled',
    expandedStateKey: 'physicianAgencyExpanded',
    childOfDriverId: 'providerWellbeing',
    calcComponent: PhysicianLocumAgencyCalc,
    trackedMeasureIds: ['agencyLocumSpend'],
    measureDefaults: {
      deltaLabel: 'Provider-weeks of locum coverage avoided',
      deltaUnit: 'weeks',
      valuePerUnitLabel: 'Weekly locum premium',
      valuePerUnitDefault: 5000,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'nursingRetention',
    label: 'RN Retention',
    shortDescription: 'Reduced documentation burden helps retain experienced nurses. Models avoided replacement cost.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingRetentionEnabled',
    expandedStateKey: 'nursingRetentionExpanded',
    calcComponent: NursingRetentionCalc,
    trackedMeasureIds: ['rnRetention', 'burnoutAssessment', 'likelihoodToStay'],
    measureDefaults: {
      deltaLabel: 'Nurses retained per year',
      deltaUnit: 'nurses',
      valuePerUnitLabel: 'Replacement cost per nurse',
      valuePerUnitDefault: 56300,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'nursingAgency',
    label: 'Travel & Agency Cost Avoidance',
    shortDescription: 'Reduced reliance on travel/agency nurses as retention stabilizes.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingAgencyEnabled',
    expandedStateKey: 'nursingAgencyExpanded',
    childOfDriverId: 'nursingRetention',
    calcComponent: NursingAgencyCalc,
    trackedMeasureIds: ['travelAgencyNurseSpend'],
    measureDefaults: {
      deltaLabel: 'Nurse-weeks of agency coverage avoided',
      deltaUnit: 'weeks',
      valuePerUnitLabel: 'Weekly agency premium',
      valuePerUnitDefault: 2500,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'nursingOvertime',
    label: 'Overtime Reduction',
    shortDescription: 'Faster charting reduces documentation-related overtime hours.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingOtEnabled',
    expandedStateKey: 'nursingOtExpanded',
    calcComponent: NursingOvertimeCalc,
    trackedMeasureIds: ['documentationOvertime', 'chartingAfterShift'],
    measureDefaults: {
      deltaLabel: 'Overtime hours eliminated per year',
      deltaUnit: 'hours',
      valuePerUnitLabel: 'Overtime hourly rate',
      valuePerUnitDefault: 75,
      valuePerUnitPrefix: '$',
      realizationDefault: 100,
      scaleAxis: 'providers',
    },
  },
  // ───── QUALITY ─────
  // Outpatient (qualitative — trimmed by R-IA-3 to 3 drivers)
  {
    id: 'opCareContinuity',
    label: 'Care Continuity',
    shortDescription: 'Better-documented handoffs improve continuity across encounters and providers.',
    quadrant: 'Quality',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opCareContinuityEnabled',
    expandedStateKey: 'opCareContinuityExpanded',
  },
  {
    id: 'opNoteStarRating',
    label: 'Note Quality (Star Rating)',
    shortDescription: 'Internal note-quality scores improve with structured AI drafting.',
    quadrant: 'Quality',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opNoteStarRatingEnabled',
    expandedStateKey: 'opNoteStarRatingExpanded',
  },
  {
    id: 'opDiagnosisCapture',
    label: 'Diagnosis Capture',
    shortDescription: 'More complete capture of conditions discussed during the visit.',
    quadrant: 'Quality',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opDiagnosisCaptureEnabled',
    expandedStateKey: 'opDiagnosisCaptureExpanded',
  },
  // ED (qualitative)
  {
    id: 'edNoteStarRating',
    label: 'ED Note Quality (Star Rating)',
    shortDescription: 'Internal note-quality scores improve in the ED with structured AI drafting.',
    quadrant: 'Quality',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edNoteStarRatingEnabled',
    expandedStateKey: 'edNoteStarRatingExpanded',
  },
  {
    id: 'edPressGaney',
    label: 'Patient Experience (Press Ganey)',
    shortDescription: 'More attentive face-time during the encounter lifts patient experience scores.',
    quadrant: 'Quality',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edPressGaneyEnabled',
    expandedStateKey: 'edPressGaneyExpanded',
  },
  {
    id: 'edProviderCommunication',
    label: 'Provider Communication',
    shortDescription: 'Patient-reported provider communication scores from HCAHPS or Press Ganey communication subscales. ED-specific patient experience signal.',
    quadrant: 'Quality',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edProviderCommunicationEnabled',
    expandedStateKey: 'edProviderCommunicationExpanded',
    trackedMeasureIds: ['pressGaney'],
  },
  // IP (qualitative)
  {
    id: 'ipNoteStarRating',
    label: 'IP Note Quality (Star Rating)',
    shortDescription: 'Internal note-quality scores improve in the inpatient setting.',
    quadrant: 'Quality',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipNoteStarRatingEnabled',
    expandedStateKey: 'ipNoteStarRatingExpanded',
  },
  {
    id: 'ipHcahpsComposite',
    label: 'HCAHPS Composite',
    shortDescription: 'Doctor-communication composite improves with attentive bedside time.',
    quadrant: 'Quality',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipHcahpsCompositeEnabled',
    expandedStateKey: 'ipHcahpsCompositeExpanded',
  },
  {
    id: 'ipReadmission',
    label: '30-Day Readmission',
    shortDescription: 'Better discharge documentation supports lower 30-day readmissions.',
    quadrant: 'Quality',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipReadmissionEnabled',
    expandedStateKey: 'ipReadmissionExpanded',
  },
  // Nursing (5 quantified + 2 qualitative)
  {
    id: 'nursingHapi',
    label: 'HAPI Prevention',
    shortDescription: 'Real-time skin and turning documentation prevents hospital-acquired pressure injuries.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingHapiEnabled',
    expandedStateKey: 'nursingHapiExpanded',
    calcComponent: NursingHapiCalc,
    measureDefaults: {
      deltaLabel: 'HAPIs prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per HAPI',
      valuePerUnitDefault: 25000,
      valuePerUnitPrefix: '$',
      realizationDefault: 85,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingFalls',
    label: 'Falls Prevention',
    shortDescription: 'Real-time risk assessments and Morse score updates reduce inpatient falls.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingFallsEnabled',
    expandedStateKey: 'nursingFallsExpanded',
    calcComponent: NursingFallsCalc,
    measureDefaults: {
      deltaLabel: 'Falls prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per fall',
      valuePerUnitDefault: 6500,
      valuePerUnitPrefix: '$',
      realizationDefault: 85,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingCauti',
    label: 'CAUTI Prevention',
    shortDescription: 'Daily catheter-necessity documentation supports earlier removal and bundle adherence.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingCautiEnabled',
    expandedStateKey: 'nursingCautiExpanded',
    calcComponent: NursingCautiCalc,
    measureDefaults: {
      deltaLabel: 'CAUTIs prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per CAUTI',
      valuePerUnitDefault: 13000,
      valuePerUnitPrefix: '$',
      realizationDefault: 80,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingClabsi',
    label: 'CLABSI Prevention',
    shortDescription: 'Bundle compliance and timely line documentation reduce central line bloodstream infections.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingClabsiEnabled',
    expandedStateKey: 'nursingClabsiExpanded',
    calcComponent: NursingClabsiCalc,
    measureDefaults: {
      deltaLabel: 'CLABSIs prevented per year',
      deltaUnit: 'events',
      valuePerUnitLabel: 'Cost per CLABSI',
      valuePerUnitDefault: 20000,
      valuePerUnitPrefix: '$',
      realizationDefault: 80,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingSepsis',
    label: 'Sepsis Bundle Compliance',
    shortDescription: 'Time-stamped vitals and antibiotic documentation lift SEP-1 bundle compliance.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'quantified',
    enabledStateKey: 'nursingSepsisEnabled',
    expandedStateKey: 'nursingSepsisExpanded',
    calcComponent: NursingSepsisCalc,
    measureDefaults: {
      deltaLabel: 'Sepsis bundle non-compliance cases avoided',
      deltaUnit: 'cases',
      valuePerUnitLabel: 'Excess cost per case',
      valuePerUnitDefault: 3500,
      valuePerUnitPrefix: '$',
      realizationDefault: 60,
      scaleAxis: 'patientDays',
    },
  },
  {
    id: 'nursingHcahps',
    label: 'HCAHPS (Nurse Communication)',
    shortDescription: 'More bedside time supports nurse-communication composite gains.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingHcahpsEnabled',
    expandedStateKey: 'nursingHcahpsExpanded',
  },
  {
    id: 'nursingMedError',
    label: 'Medication Error Reduction',
    shortDescription: 'Cleaner real-time documentation reduces medication-related near misses and errors.',
    quadrant: 'Quality',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingMedErrorEnabled',
    expandedStateKey: 'nursingMedErrorExpanded',
  },

  // ───── REVENUE ─────
  {
    id: 'wrvu',
    label: 'wRVU Capture',
    shortDescription: 'When notes fully reflect visit complexity, E/M levels often code higher.',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'quantified',
    enabledStateKey: 'wrvuEnabled',
    expandedStateKey: 'wrvuExpanded',
    calcComponent: WrvuCalc,
    trackedMeasureIds: ['wrvu'],
    measureDefaults: {
      deltaLabel: 'wRVU lift per visit',
      deltaUnit: 'wRVU',
      valuePerUnitLabel: 'Conversion factor',
      valuePerUnitDefault: 50,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'edEmLevel',
    label: 'E&M Level Accuracy',
    shortDescription: 'Capture the true complexity of ED visits supporting accurate E/M leveling.',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'quantified',
    enabledStateKey: 'wrvuEnabled',
    expandedStateKey: 'wrvuExpanded',
    calcComponent: WrvuCalc,
    trackedMeasureIds: ['wrvuPerShift', 'emLevel'],
    measureDefaults: {
      deltaLabel: 'E/M wRVU lift per visit',
      deltaUnit: 'wRVU',
      valuePerUnitLabel: 'Conversion factor',
      valuePerUnitDefault: 50,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'hccCapture',
    label: 'HCC Capture',
    shortDescription: 'Recapture missed diagnoses for the Medicare Advantage population.',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'quantified',
    enabledStateKey: 'hccEnabled',
    expandedStateKey: 'hccExpanded',
    calcComponent: HccCaptureCalc,
    trackedMeasureIds: ['hccCapture'],
    measureDefaults: {
      deltaLabel: 'HCCs documented',
      deltaUnit: 'HCCs',
      valuePerUnitLabel: 'Value per HCC',
      valuePerUnitDefault: 1500,
      valuePerUnitPrefix: '$',
      realizationDefault: 40,
      scaleAxis: 'providers',
    },
  },
  {
    id: 'denialPrevention',
    label: 'Denial Prevention',
    shortDescription: 'Reduce documentation-related claim denials.',
    quadrant: 'Revenue',
    settings: ['outpatient', 'ed'],
    visibility: 'quantified',
    enabledStateKey: 'denialsEnabled',
    expandedStateKey: 'denialsExpanded',
    calcComponent: DenialPreventionCalc,
    trackedMeasureIds: ['cleanClaim', 'medicalNecessityDenial'],
    measureDefaults: {
      deltaLabel: 'Denials prevented',
      deltaUnit: 'claims',
      valuePerUnitLabel: 'Avg claim value',
      valuePerUnitDefault: 500,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'drgAccuracy',
    label: 'DRG Accuracy',
    shortDescription: 'Capture clinical complexity discussed during care that affects DRG assignment.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'ipDrgEnabled',
    expandedStateKey: 'ipDrgExpanded',
    calcComponent: DrgAccuracyCalc,
    trackedMeasureIds: ['drgAccuracy', 'ccMccCapture', 'caseMixIndex'],
    measureDefaults: {
      deltaLabel: 'Admissions with DRG lift',
      deltaUnit: 'admissions',
      valuePerUnitLabel: 'Avg DRG payment lift',
      valuePerUnitDefault: 4000,
      valuePerUnitPrefix: '$',
      realizationDefault: 33,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'cdiQueryReduction',
    label: 'CDI Query Reduction',
    shortDescription: 'Fewer queries when documentation is complete upfront.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'ipCdiEnabled',
    expandedStateKey: 'ipCdiExpanded',
    calcComponent: CdiQueryReductionCalc,
    trackedMeasureIds: ['cdiQueryReduction'],
    measureDefaults: {
      deltaLabel: 'Queries avoided',
      deltaUnit: 'queries',
      valuePerUnitLabel: 'Cost per query',
      valuePerUnitDefault: 50,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'obsDefense',
    label: 'Observation / IP Status Defense',
    shortDescription: 'Defensible documentation supporting admission status determinations.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'ipObsDefenseEnabled',
    expandedStateKey: 'ipObsDefenseExpanded',
    calcComponent: ObsDefenseCalc,
    trackedMeasureIds: ['medicalNecessityDenial'],
    measureDefaults: {
      deltaLabel: 'Appeal-defensible denials',
      deltaUnit: 'claims',
      valuePerUnitLabel: 'Avg contested claim value',
      valuePerUnitDefault: 10000,
      valuePerUnitPrefix: '$',
      realizationDefault: 25,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'emCodingAccuracy',
    label: 'E/M Coding Accuracy',
    shortDescription: 'Right-code clinical complexity from ambient capture, including consults and progress notes.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'quantified',
    enabledStateKey: 'ipEmCodingEnabled',
    expandedStateKey: 'ipEmCodingExpanded',
    calcComponent: EmCodingCalc,
    trackedMeasureIds: ['emLevel'],
    measureDefaults: {
      deltaLabel: 'Encounters captured',
      deltaUnit: 'encounters',
      valuePerUnitLabel: 'Avg revenue lift per encounter',
      valuePerUnitDefault: 35,
      valuePerUnitPrefix: '$',
      realizationDefault: 75,
      scaleAxis: 'encounters',
    },
  },
  {
    id: 'nursingCdiResponse',
    label: 'CDI Query Response',
    shortDescription: 'Faster, more complete nursing documentation supports DRG accuracy and timeliness.',
    quadrant: 'Revenue',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingCdiResponseEnabled',
    expandedStateKey: 'nursingCdiResponseExpanded',
    trackedMeasureIds: ['cdiQueryResponseRate'],
  },
  {
    id: 'nursingDocCompletion',
    label: 'Documentation Completion',
    shortDescription: 'Timely nursing documentation reduces billing delays and discharge holds.',
    quadrant: 'Revenue',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingDocCompletionEnabled',
    expandedStateKey: 'nursingDocCompletionExpanded',
    trackedMeasureIds: ['nursingDocCompletion'],
  },

  // ───── R-IA-2 / R-IA-3 — Curated qualitative drivers (toggleable, no $ math) ─────
  // OP Capacity (qualitative — 3 drivers, R-IA-3 trim)
  {
    id: 'opThirdNextAvailable',
    label: '3rd Next Available',
    shortDescription: 'Days until the third next available appointment slot. A standard access metric.',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opThirdNextAvailableEnabled',
    expandedStateKey: 'opThirdNextAvailableExpanded',
    trackedMeasureIds: ['thirdNextAvailable'],
  },
  {
    id: 'opSameDayAccess',
    label: 'Same-Day or Urgent Access Slots',
    shortDescription: 'Number of same-day or urgent slots opened on the schedule. A measure of access for patients who need to be seen quickly.',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opSameDayAccessEnabled',
    expandedStateKey: 'opSameDayAccessExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'opExtendedVisitTime',
    label: 'Extended Visit Time for Complex Patients',
    shortDescription: 'Average minutes spent with complex patients during their visit. Tracks whether reclaimed time is reinvested in deeper care for harder cases.',
    quadrant: 'Capacity',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opExtendedVisitTimeEnabled',
    expandedStateKey: 'opExtendedVisitTimeExpanded',
    trackedMeasureIds: [],
  },

  // OP Workforce (qualitative — 3 drivers, R-IA-3 trim; Burnout Score listed last)
  {
    id: 'opAfterHoursDoc',
    label: 'After-Hours Documentation',
    shortDescription: 'Time providers spend in the EHR outside scheduled clinical hours. A widely used signal for documentation burden.',
    quadrant: 'Workforce',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opAfterHoursDocEnabled',
    expandedStateKey: 'opAfterHoursDocExpanded',
    trackedMeasureIds: ['workOutsideWorkEmpirical'],
  },
  {
    id: 'opNotesBeforeLeaving',
    label: 'Notes Completed Before Leaving the Clinic',
    shortDescription: 'Share of encounter notes signed before the provider leaves the clinic that day. Tracks the shift away from after-hours charting.',
    quadrant: 'Workforce',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opNotesBeforeLeavingEnabled',
    expandedStateKey: 'opNotesBeforeLeavingExpanded',
    trackedMeasureIds: [],
  },
  {
    id: 'opBurnoutTracking',
    label: 'Burnout Score',
    shortDescription: 'Score from a validated burnout instrument (e.g., Maslach Burnout Inventory). Tracked as a leading indicator for retention.',
    quadrant: 'Workforce',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opBurnoutTrackingEnabled',
    expandedStateKey: 'opBurnoutTrackingExpanded',
    trackedMeasureIds: ['burnoutAssessment'],
  },

  // OP Revenue (qualitative — 3 drivers, R-IA-3 trim — all new)
  {
    id: 'opEmLevelDistribution',
    label: 'E&M Level Distribution Shift',
    shortDescription: 'Distribution of E/M codes assigned across encounters. A shift toward higher-level codes can indicate documentation more fully reflects visit complexity.',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opEmLevelDistributionEnabled',
    expandedStateKey: 'opEmLevelDistributionExpanded',
    trackedMeasureIds: ['emLevel'],
  },
  {
    id: 'opCdiQueryTrend',
    label: 'CDI Query Volume Trend',
    shortDescription: 'Volume of CDI queries returned to providers post-visit. Decreasing query volume often signals more complete documentation at the point of care.',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opCdiQueryTrendEnabled',
    expandedStateKey: 'opCdiQueryTrendExpanded',
    trackedMeasureIds: ['opCdiQueryReduction'],
  },
  {
    id: 'opCodingSpecificity',
    label: 'Coding Specificity Improvement',
    shortDescription: 'Share of diagnoses coded to the highest available ICD-10 specificity. Tracked as a downstream signal of clinical detail captured in notes.',
    quadrant: 'Revenue',
    settings: ['outpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'opCodingSpecificityEnabled',
    expandedStateKey: 'opCodingSpecificityExpanded',
    trackedMeasureIds: ['diagnosisSpecificity'],
  },

  // ED Capacity (qualitative — 3 drivers, expanded by R-IA-4)
  {
    id: 'edDoorToProvider',
    label: 'Door-to-Provider Time',
    shortDescription: 'Minutes from patient arrival to first provider contact. An upstream indicator for LWBS and patient experience.',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edDoorToProviderEnabled',
    expandedStateKey: 'edDoorToProviderExpanded',
    trackedMeasureIds: ['doorToProvider'],
  },
  {
    id: 'edDoorToDisposition',
    label: 'Door-to-Disposition Time',
    shortDescription: 'Minutes from patient arrival to admit/discharge decision. A throughput indicator that reflects the full ED decision cycle.',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edDoorToDispositionEnabled',
    expandedStateKey: 'edDoorToDispositionExpanded',
    trackedMeasureIds: ['doorToDisposition'],
  },
  {
    id: 'edBedTurnover',
    label: 'Bed Turnover Time',
    shortDescription: 'Minutes between patient discharge and bed becoming ready for the next patient. Tracks ED operational efficiency and boarding pressure.',
    quadrant: 'Capacity',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edBedTurnoverEnabled',
    expandedStateKey: 'edBedTurnoverExpanded',
    trackedMeasureIds: [],
  },

  // ED Workforce (qualitative — 3 drivers, expanded by R-IA-4)
  {
    id: 'edAfterHoursDoc',
    label: 'After-Hours Documentation',
    shortDescription: 'Time providers spend in the EHR outside scheduled shift hours. A widely used signal for documentation burden in shift-based settings.',
    quadrant: 'Workforce',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edAfterHoursDocEnabled',
    expandedStateKey: 'edAfterHoursDocExpanded',
    trackedMeasureIds: ['workOutsideWorkEmpirical'],
  },
  {
    id: 'edBurnoutTracking',
    label: 'Burnout Score',
    shortDescription: 'Score from a validated burnout instrument. Tracked as a leading indicator for retention.',
    quadrant: 'Workforce',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edBurnoutTrackingEnabled',
    expandedStateKey: 'edBurnoutTrackingExpanded',
    trackedMeasureIds: ['burnoutAssessment'],
  },
  {
    id: 'edLikelihoodToStay',
    label: 'Likelihood to Stay',
    shortDescription: 'Survey item measuring intent to remain in current role over a defined timeframe.',
    quadrant: 'Workforce',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edLikelihoodToStayEnabled',
    expandedStateKey: 'edLikelihoodToStayExpanded',
    trackedMeasureIds: ['likelihoodToStay'],
  },

  // ED Revenue (qualitative — 3 drivers, expanded by R-IA-4)
  {
    id: 'edCleanClaim',
    label: 'Clean Claim Rate',
    shortDescription: 'Share of ED claims accepted on first submission. Tracked as a downstream signal of documentation completeness.',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edCleanClaimEnabled',
    expandedStateKey: 'edCleanClaimExpanded',
    trackedMeasureIds: ['cleanClaim'],
  },
  {
    id: 'edEmLevelDistribution',
    label: 'E&M Level Distribution Shift',
    shortDescription: 'Distribution of ED E/M codes (99281-99285) across encounters. A shift toward higher-level codes can indicate documentation more fully reflects visit complexity.',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edEmLevelDistributionEnabled',
    expandedStateKey: 'edEmLevelDistributionExpanded',
    trackedMeasureIds: ['emLevel'],
  },
  {
    id: 'edCdiQueryTrend',
    label: 'CDI Query Volume Trend',
    shortDescription: 'Volume of CDI queries returned to ED providers post-visit. Decreasing query volume often signals more complete documentation at the point of care.',
    quadrant: 'Revenue',
    settings: ['ed'],
    visibility: 'qualitative',
    enabledStateKey: 'edCdiQueryTrendEnabled',
    expandedStateKey: 'edCdiQueryTrendExpanded',
    trackedMeasureIds: [],
  },

  // IP Capacity (qualitative)
  {
    id: 'ipAlosTracking',
    label: 'Average Length of Stay',
    shortDescription: 'Average days per inpatient admission. Tracked as a flow indicator alongside discharge timing.',
    quadrant: 'Capacity',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipAlosTrackingEnabled',
    expandedStateKey: 'ipAlosTrackingExpanded',
    trackedMeasureIds: ['avgLengthOfStay'],
  },

  // IP Workforce (qualitative)
  {
    id: 'ipBurnoutTracking',
    label: 'Burnout Score',
    shortDescription: 'Score from a validated burnout instrument. Tracked as a leading indicator for hospitalist retention.',
    quadrant: 'Workforce',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipBurnoutTrackingEnabled',
    expandedStateKey: 'ipBurnoutTrackingExpanded',
    trackedMeasureIds: ['burnoutAssessment'],
  },
  {
    id: 'ipLikelihoodToStay',
    label: 'Likelihood to Stay',
    shortDescription: 'Survey item measuring intent to remain in current role over a defined timeframe.',
    quadrant: 'Workforce',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipLikelihoodToStayEnabled',
    expandedStateKey: 'ipLikelihoodToStayExpanded',
    trackedMeasureIds: ['likelihoodToStay'],
  },

  // IP Revenue (qualitative)
  {
    id: 'ipCmiTracking',
    label: 'Case Mix Index',
    shortDescription: 'Weighted average of DRG relative weights. Tracked as a downstream signal of CC/MCC capture and DRG accuracy.',
    quadrant: 'Revenue',
    settings: ['inpatient'],
    visibility: 'qualitative',
    enabledStateKey: 'ipCmiTrackingEnabled',
    expandedStateKey: 'ipCmiTrackingExpanded',
    trackedMeasureIds: ['caseMixIndex'],
  },

  // Nursing Workforce (qualitative)
  {
    id: 'nursingLikelihoodToStay',
    label: 'Likelihood to Stay',
    shortDescription: 'Survey item measuring intent to remain in current role over a defined timeframe.',
    quadrant: 'Workforce',
    settings: ['nursing'],
    visibility: 'qualitative',
    enabledStateKey: 'nursingLikelihoodToStayEnabled',
    expandedStateKey: 'nursingLikelihoodToStayExpanded',
    trackedMeasureIds: ['likelihoodToStay'],
  },
];

export function getDriversForPage(quadrant: ExploreQuadrant, setting: ExploreSetting): ExploreDriver[] {
  return EXPLORE_DRIVERS.filter(d => d.quadrant === quadrant && d.settings.includes(setting));
}

export function isDriverEnabled(driver: ExploreDriver, state: ExploreState): boolean {
  const td = state.timeDriverInputs as any;
  const dq = state.docQualityInputs as any;
  return Boolean(td[driver.enabledStateKey] ?? dq[driver.enabledStateKey]);
}
