import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface DriverDetail {
  id: string;
  name: string;
  value: number;
  category: 'labor' | 'revenue';
  theory: string;
  keyVariables?: { label: string; value: string }[];
  formula?: string;
  steps?: { label: string; calculation: string; result: string }[];
}

export interface PremiumPDFData {
  setting: string;
  unitName: string;
  unitNamePlural: string;
  providers: number;
  encounters: number;
  utilization: number;
  totalValue: number;
  investment: number;
  netGain: number;
  roi: number;
  costPerProvider: number;
  hoursReturned: number;
  additionalVisits: number;
  timeSaved: number;
  laborDrivers: { name: string; value: number; description: string }[];
  revenueDrivers: { name: string; value: number; description: string }[];
  laborTotal: number;
  revenueTotal: number;
  laborPct: number;
  revenuePct: number;
  year1: number;
  year2: number;
  year3: number;
  threeYearValue: number;
  threeYearCost: number;
  threeYearNet: number;
  fullScaleProviders: number;
  fullScaleUtil: number;
  fullScaleValue: number;
  fullScaleROI: number;
  networkEffect: number;
  qualitativeDrivers?: string[];
  driverDetails?: DriverDetail[];
  organizationName?: string;
}

// Premium color palette - Abridge brand
const COLORS = {
  red: [233, 78, 61] as [number, number, number],       // #E94E3D Abridge red
  redLight: [254, 242, 240] as [number, number, number],
  green: [16, 185, 129] as [number, number, number],    // #10B981 accent green
  greenLight: [236, 253, 245] as [number, number, number],
  black: [26, 26, 26] as [number, number, number],      // #1A1A1A
  darkGray: [55, 65, 81] as [number, number, number],
  mediumGray: [107, 114, 128] as [number, number, number],
  lightGray: [156, 163, 175] as [number, number, number],
  warmGray: [245, 245, 245] as [number, number, number], // #F5F5F5
  subtleGray: [243, 244, 246] as [number, number, number],
  borderGray: [229, 231, 235] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  blue: [59, 130, 246] as [number, number, number],
  blueLight: [239, 246, 255] as [number, number, number],
};

const formatCurrency = (num: number): string => {
  return '$' + Math.round(Math.abs(num)).toLocaleString();
};

const formatCurrencyWithPlus = (num: number): string => {
  const prefix = num >= 0 ? '+$' : '-$';
  return prefix + Math.round(Math.abs(num)).toLocaleString();
};

const formatCurrencyShort = (num: number): string => {
  if (Math.abs(num) >= 1000000) return '$' + (num / 1000000).toFixed(1) + 'M';
  if (Math.abs(num) >= 1000) return '$' + Math.round(num / 1000).toLocaleString() + 'K';
  return '$' + Math.round(num).toLocaleString();
};

const formatNumber = (num: number): string => {
  return Math.round(num).toLocaleString();
};

export async function generatePremiumPDF(data: PremiumPDFData): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let currentPage = 1;
  
  const allDrivers = [...data.laborDrivers, ...data.revenueDrivers];
  const driverPagesNeeded = Math.max(2, Math.ceil(allDrivers.length / 2)); // At least 2 driver pages
  const totalPages = 6; // Fixed 6-page structure: Cover + Org + 2 Driver pages + Investment + Methodology
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const eligibleEncounters = Math.round(data.encounters * data.utilization / 100);
  const orgName = data.organizationName || 'Your Organization';
  const valuePerProvider = data.providers > 0 ? data.totalValue / data.providers : 0;
  const netPerProvider = data.providers > 0 ? data.netGain / data.providers : 0;

  // Helper: Draw header with ABRIDGE logo
  const drawHeader = () => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.red);
    doc.text('ABRIDGE', margin, 15);
    
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.mediumGray);
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.setting} ROI Assessment`, pageWidth - margin, 15, { align: 'right' });
    
    doc.setDrawColor(...COLORS.borderGray);
    doc.setLineWidth(0.3);
    doc.line(margin, 20, pageWidth - margin, 20);
  };

  // Helper: Draw footer
  const drawFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.lightGray);
    doc.text('Generated by Abridge ROI Calculator', margin, pageHeight - 10);
    doc.text(`Page ${currentPage} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  };

  // Helper: Draw a box with border
  const drawBox = (x: number, y: number, w: number, h: number, fillColor?: [number, number, number]) => {
    if (fillColor) {
      doc.setFillColor(...fillColor);
      doc.setDrawColor(...COLORS.borderGray);
      doc.roundedRect(x, y, w, h, 2, 2, 'FD');
    } else {
      doc.setDrawColor(...COLORS.borderGray);
      doc.setLineWidth(0.3);
      doc.roundedRect(x, y, w, h, 2, 2, 'S');
    }
  };

  // Helper: Draw a horizontal bar
  const drawBar = (x: number, y: number, width: number, height: number, fillPct: number, fillColor: [number, number, number], bgColor: [number, number, number]) => {
    doc.setFillColor(...bgColor);
    doc.roundedRect(x, y, width, height, 1, 1, 'F');
    if (fillPct > 0) {
      doc.setFillColor(...fillColor);
      doc.roundedRect(x, y, width * Math.min(fillPct, 1), height, 1, 1, 'F');
    }
  };

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 1: COVER WITH RESULTS
  // ═══════════════════════════════════════════════════════════════════════════
  
  // Giant faint "A" watermark (simulated with large text)
  doc.setFontSize(350);
  doc.setTextColor(245, 245, 245);
  doc.text('A', -30, 220);
  
  // Top section: Logo and title
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.red);
  doc.text('ABRIDGE', margin, 30);
  
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(data.setting.toUpperCase(), pageWidth / 2, 55, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('ROI Assessment', pageWidth / 2, 65, { align: 'center' });
  
  // Horizontal line
  doc.setDrawColor(...COLORS.borderGray);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, 72, pageWidth / 2 + 40, 72);
  
  // Organization info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(orgName, pageWidth / 2, 82, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(`${data.providers} ${data.unitNamePlural} · ${formatNumber(data.encounters)} Encounters`, pageWidth / 2, 90, { align: 'center' });
  doc.text(`Prepared ${today}`, pageWidth / 2, 97, { align: 'center' });
  
  // YOUR RESULTS AT A GLANCE
  let yPos = 115;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR RESULTS AT A GLANCE', margin, yPos);
  
  // 4 metric cards
  yPos += 8;
  const cardWidth = (contentWidth - 15) / 4;
  const cardHeight = 32;
  
  const metrics = [
    { value: formatCurrencyWithPlus(data.netGain), label: 'Net Annual', sublabel: 'Gain', color: COLORS.green },
    { value: data.roi.toFixed(1) + 'x', label: 'Return on', sublabel: 'Investment', color: COLORS.black },
    { value: formatNumber(data.hoursReturned), label: 'Hours', sublabel: 'Returned', color: COLORS.black },
    { value: formatCurrency(netPerProvider), label: 'Per', sublabel: data.unitName, color: COLORS.black },
  ];
  
  metrics.forEach((m, i) => {
    const cardX = margin + i * (cardWidth + 5);
    drawBox(cardX, yPos, cardWidth, cardHeight, COLORS.warmGray);
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...m.color);
    doc.text(m.value, cardX + cardWidth / 2, yPos + 13, { align: 'center' });
    
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(m.label, cardX + cardWidth / 2, yPos + 21, { align: 'center' });
    doc.text(m.sublabel, cardX + cardWidth / 2, yPos + 27, { align: 'center' });
  });
  
  // VALUE COMPOSITION section
  yPos += cardHeight + 15;
  drawBox(margin, yPos, contentWidth, 50, COLORS.white);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('VALUE COMPOSITION', margin + 8, yPos + 10);
  
  // Total value bar
  const barX = margin + 8;
  const barWidth = contentWidth - 80;
  const totalMax = Math.max(data.totalValue, data.investment);
  
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.darkGray);
  doc.text(formatCurrencyShort(data.totalValue) + ' Total', barX + barWidth + 5, yPos + 20);
  drawBar(barX, yPos + 15, barWidth, 6, data.totalValue / totalMax, COLORS.green, COLORS.subtleGray);
  
  doc.text(formatCurrencyShort(data.investment) + ' Investment', barX + barWidth + 5, yPos + 32);
  drawBar(barX, yPos + 27, barWidth, 6, data.investment / totalMax, COLORS.mediumGray, COLORS.subtleGray);
  
  // Labor vs Revenue breakdown
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.darkGray);
  const laborBarW = (barWidth - 10) / 2;
  doc.text(`Labor & Efficiency (${data.laborPct}%)`, barX, yPos + 44);
  doc.text(`Revenue & Quality (${data.revenuePct}%)`, barX + laborBarW + 15, yPos + 44);
  
  drawBar(barX, yPos + 46, laborBarW, 4, data.laborPct / 100, COLORS.blue, COLORS.subtleGray);
  drawBar(barX + laborBarW + 15, yPos + 46, laborBarW, 4, data.revenuePct / 100, COLORS.green, COLORS.subtleGray);
  
  doc.setFontSize(8);
  doc.text(formatCurrency(data.laborTotal), barX, yPos + 56);
  doc.text(formatCurrency(data.revenueTotal), barX + laborBarW + 15, yPos + 56);
  
  // THE FRAME quote box
  yPos += 70;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('THE FRAME', margin, yPos);
  
  yPos += 5;
  drawBox(margin, yPos, contentWidth, 65, COLORS.warmGray);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.darkGray);
  
  const frameLines = [
    '"Most organizations ask \'What\'s the ROI of ambient AI?\'',
    '',
    'That\'s the wrong question.',
    '',
    'The right question is: \'Which value drivers matter most',
    'to us, and how do we capture them?\'',
    '',
    'This assessment models your specific priorities:'
  ];
  
  frameLines.forEach((line, i) => {
    doc.text(line, margin + 10, yPos + 10 + i * 5);
  });
  
  // Selected drivers as checkmarks
  doc.setFont('helvetica', 'normal');
  const selectedDrivers = allDrivers.map(d => d.name);
  let checkY = yPos + 50;
  let checkX = margin + 10;
  selectedDrivers.forEach((name, i) => {
    if (i > 0 && i % 2 === 0) {
      checkY += 6;
      checkX = margin + 10;
    }
    doc.setTextColor(...COLORS.green);
    doc.text('>', checkX, checkY);
    doc.setTextColor(...COLORS.darkGray);
    doc.text(name, checkX + 5, checkY);
    checkX += 80;
  });
  
  drawFooter();
  
  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 2: YOUR ORGANIZATION + VALUE DRIVER FRAMEWORK
  // ═══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  currentPage++;
  drawHeader();
  
  yPos = 30;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR ORGANIZATION', margin, yPos);
  
  yPos += 8;
  drawBox(margin, yPos, contentWidth, 75, COLORS.white);
  
  // Deployment Scope and Baseline side by side
  const scopeBoxW = 55;
  const baselineBoxW = 60;
  
  // DEPLOYMENT SCOPE
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('DEPLOYMENT SCOPE', margin + 10, yPos + 12);
  
  drawBox(margin + 10, yPos + 16, scopeBoxW / 2 - 3, 22, COLORS.warmGray);
  drawBox(margin + 10 + scopeBoxW / 2 + 2, yPos + 16, scopeBoxW / 2 - 3, 22, COLORS.warmGray);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(data.providers.toString(), margin + 10 + (scopeBoxW / 4), yPos + 28, { align: 'center' });
  doc.text(formatNumber(data.encounters), margin + 10 + scopeBoxW / 2 + 2 + (scopeBoxW / 4), yPos + 28, { align: 'center' });
  
  doc.setFontSize(6);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(data.unitNamePlural, margin + 10 + (scopeBoxW / 4), yPos + 34, { align: 'center' });
  doc.text('Encounters', margin + 10 + scopeBoxW / 2 + 2 + (scopeBoxW / 4), yPos + 34, { align: 'center' });
  
  // YOUR BASELINE
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('YOUR BASELINE', margin + scopeBoxW + 30, yPos + 12);
  
  drawBox(margin + scopeBoxW + 30, yPos + 16, baselineBoxW, 30, COLORS.warmGray);
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(formatNumber(eligibleEncounters), margin + scopeBoxW + 30 + baselineBoxW / 2, yPos + 30, { align: 'center' });
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Eligible Encounters', margin + scopeBoxW + 30 + baselineBoxW / 2, yPos + 38, { align: 'center' });
  doc.text('per year', margin + scopeBoxW + 30 + baselineBoxW / 2, yPos + 43, { align: 'center' });
  
  // Utilization assumption
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('UTILIZATION ASSUMPTION', margin + 10, yPos + 52);
  
  // Radio buttons for utilization
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  const utilOptions = [
    { label: 'Conservative (50%)', val: 50 },
    { label: 'Typical (65%)', val: 65 },
    { label: 'Aggressive (80%)', val: 80 },
  ];
  
  let utilX = margin + 12;
  utilOptions.forEach((opt) => {
    const isSelected = data.utilization === opt.val;
    doc.setDrawColor(...COLORS.mediumGray);
    doc.circle(utilX, yPos + 60, 2, isSelected ? 'FD' : 'S');
    if (isSelected) {
      doc.setFillColor(...COLORS.green);
      doc.circle(utilX, yPos + 60, 1.2, 'F');
    }
    doc.setTextColor(...COLORS.darkGray);
    doc.text(opt.label, utilX + 4, yPos + 61);
    utilX += 42;
  });
  
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(`At ${data.utilization}% utilization, we assume Abridge is used for ${data.utilization}% of eligible encounters.`, margin + 10, yPos + 70);
  
  // HOW WE THINK ABOUT VALUE
  yPos += 90;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('HOW WE THINK ABOUT VALUE', margin, yPos);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Ambient documentation creates value through multiple channels. Most organizations focus on', margin, yPos + 8);
  doc.text('one or two. The complete picture requires understanding all of them.', margin, yPos + 14);
  
  // Two-column framework
  yPos += 22;
  const frameworkWidth = (contentWidth - 5) / 2;
  
  // LABOR & EFFICIENCY column
  drawBox(margin, yPos, frameworkWidth, 55, COLORS.blueLight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.blue);
  doc.text('LABOR & EFFICIENCY', margin + 5, yPos + 10);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Value from time returned', margin + 5, yPos + 16);
  
  const laborOptions = ['Patient Access', 'Overtime & Locum Savings', 'Clinician Retention'];
  laborOptions.forEach((opt, i) => {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    const hasDriver = data.laborDrivers.some(d => d.name.includes(opt.split(' ')[0]));
    doc.setTextColor(...(hasDriver ? COLORS.blue : COLORS.mediumGray));
    doc.text((hasDriver ? '>' : 'o') + ' ' + opt, margin + 8, yPos + 26 + i * 10);
    doc.setTextColor(...COLORS.lightGray);
    doc.setFontSize(6);
    if (i === 0) doc.text('Time -> capacity -> visits', margin + 10, yPos + 31);
    if (i === 1) doc.text('Reduced after-hours work', margin + 10, yPos + 41);
    if (i === 2) doc.text('Burnout -> turnover costs', margin + 10, yPos + 51);
  });
  
  // REVENUE & QUALITY column
  drawBox(margin + frameworkWidth + 5, yPos, frameworkWidth, 55, COLORS.greenLight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text('REVENUE & QUALITY', margin + frameworkWidth + 10, yPos + 10);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Value from better documentation', margin + frameworkWidth + 10, yPos + 16);
  
  const revenueOptions = ['Accurate Level of Service', 'HCC & Chronic Condition', 'Documentation-Related Denials'];
  revenueOptions.forEach((opt, i) => {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    const hasDriver = data.revenueDrivers.some(d => d.name.includes(opt.split(' ')[0]) || d.name.includes(opt.split('-')[0].trim()));
    doc.setTextColor(...(hasDriver ? COLORS.green : COLORS.mediumGray));
    doc.text((hasDriver ? '>' : 'o') + ' ' + opt, margin + frameworkWidth + 12, yPos + 26 + i * 10);
    doc.setTextColor(...COLORS.lightGray);
    doc.setFontSize(6);
    if (i === 0) doc.text('Complexity -> coding -> revenue', margin + frameworkWidth + 14, yPos + 31);
    if (i === 1) doc.text('Risk adjustment capture', margin + frameworkWidth + 14, yPos + 41);
    if (i === 2) doc.text('Clearer MDM -> fewer denials', margin + frameworkWidth + 14, yPos + 51);
  });
  
  // YOUR SELECTED PRIORITIES
  yPos += 65;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(`YOUR SELECTED PRIORITIES (${allDrivers.length} of 6)`, margin, yPos);
  
  yPos += 6;
  drawBox(margin, yPos, contentWidth, 8 + allDrivers.length * 8 + 12, COLORS.warmGray);
  
  let priorityY = yPos + 8;
  allDrivers.forEach((driver) => {
    const pct = data.totalValue > 0 ? Math.round((driver.value / data.totalValue) * 100) : 0;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.green);
    doc.text('>', margin + 5, priorityY);
    doc.setTextColor(...COLORS.black);
    doc.text(driver.name, margin + 10, priorityY);
    doc.text(formatCurrency(driver.value), margin + 100, priorityY);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(`${pct}% of total value`, margin + 135, priorityY);
    priorityY += 8;
  });
  
  doc.setDrawColor(...COLORS.borderGray);
  doc.line(margin + 5, priorityY, margin + contentWidth - 10, priorityY);
  priorityY += 6;
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('TOTAL ANNUAL VALUE', margin + 10, priorityY);
  doc.text(formatCurrency(data.totalValue), margin + 100, priorityY);
  
  drawFooter();
  
  // ═══════════════════════════════════════════════════════════════════════════
  // PAGES 3-4: VALUE DRIVER DEEP DIVES (2 per page)
  // ═══════════════════════════════════════════════════════════════════════════
  
  const getDriverTheory = (driverName: string): string => {
    const name = driverName.toLowerCase();
    if (name.includes('patient access')) {
      return 'When clinicians spend less time on documentation, they have capacity to see additional patients. Not all saved time converts to visits—scheduling, room availability, and demand limit realization—but even a modest portion creates meaningful revenue.';
    } else if (name.includes('level of service') || name.includes('wrvu') || name.includes('e/m')) {
      return 'Physicians under time pressure document less than the full clinical picture. AI-assisted documentation captures the complexity that supports accurate coding—not upcoding, just getting credit for work already done.';
    } else if (name.includes('retention') || name.includes('burnout')) {
      return 'Documentation burden is the #1 driver of physician burnout. Reducing this burden improves satisfaction and retention. Replacing a physician costs $400K-$800K+ when you factor in recruiting, lost revenue during vacancy, and onboarding.';
    } else if (name.includes('denial')) {
      return 'Most denials are recoverable—you appeal, you win, it just costs time. But a portion of documentation-related denials are written off without appeal, either because the MDM can\'t support it or the rework cost exceeds the claim value.';
    } else if (name.includes('overtime') || name.includes('locum')) {
      return 'When documentation work extends beyond regular hours, organizations either pay overtime or bring in expensive locum coverage. Reducing documentation burden cuts this unnecessary cost.';
    } else if (name.includes('hcc') || name.includes('chronic')) {
      return 'Complete documentation captures all relevant chronic conditions, improving risk adjustment scores and associated reimbursement under value-based care arrangements.';
    }
    return 'This value driver captures the financial impact of documentation improvements in this area.';
  };
  
  const getDriverSteps = (driver: { name: string; value: number }): { step: string; calculation: string }[] => {
    const name = driver.name.toLowerCase();
    const hourlyRate = 150;
    const timeSavedMin = 2.5;
    const timeSavedHrs = (eligibleEncounters * timeSavedMin) / 60;
    
    if (name.includes('patient access')) {
      const allocatedHrs = Math.round(timeSavedHrs * 0.25);
      const convertedHrs = Math.round(allocatedHrs * 0.6);
      const visits = Math.round(convertedHrs * 2); // 30 min per visit
      const revenuePerVisit = driver.value > 0 ? Math.round(driver.value / visits) : 200;
      return [
        { step: 'Step 1: Time Returned', calculation: `${formatNumber(eligibleEncounters)} enc x ${timeSavedMin} min = ${formatNumber(Math.round(timeSavedHrs))} hours` },
        { step: 'Step 2: Time Allocated to Access (25%)', calculation: `${formatNumber(Math.round(timeSavedHrs))} hrs x 25% = ${formatNumber(allocatedHrs)} hours` },
        { step: 'Step 3: Conversion to Visits (60%)', calculation: `${formatNumber(allocatedHrs)} hrs x 60% = ${formatNumber(convertedHrs)} hours patient care` },
        { step: 'Step 4: New Visits', calculation: `${formatNumber(convertedHrs)} hrs / 30 min/visit = ${formatNumber(visits)} additional visits` },
        { step: 'Step 5: Revenue Impact', calculation: `${formatNumber(visits)} visits x $${revenuePerVisit}/visit = ${formatCurrency(driver.value)}` },
      ];
    } else if (name.includes('level of service') || name.includes('wrvu') || name.includes('e/m')) {
      const baseWRVU = eligibleEncounters * 1.5;
      const wrvuGain = Math.round(baseWRVU * 0.05);
      return [
        { step: 'Step 1: Baseline wRVUs', calculation: `${formatNumber(eligibleEncounters)} encounters x 1.5 avg wRVU = ${formatNumber(Math.round(baseWRVU))} wRVUs` },
        { step: 'Step 2: wRVU Improvement (5%)', calculation: `${formatNumber(Math.round(baseWRVU))} wRVUs x 5% = ${formatNumber(wrvuGain)} wRVU gain` },
        { step: 'Step 3: Revenue Impact', calculation: `${formatNumber(wrvuGain)} wRVU x $33 conversion factor = ${formatCurrency(driver.value)}` },
      ];
    } else if (name.includes('retention') || name.includes('burnout')) {
      const turnover = data.providers * 0.06;
      const burnoutRelated = turnover * 0.45;
      const attributed = burnoutRelated * 0.3;
      return [
        { step: 'Step 1: Baseline Turnover', calculation: `${data.providers} providers x 6% turnover = ${turnover.toFixed(1)} departures/year` },
        { step: 'Step 2: Burnout-Related Departures (45%)', calculation: `${turnover.toFixed(1)} departures x 45% = ${burnoutRelated.toFixed(2)} preventable` },
        { step: 'Step 3: Abridge Attribution (30%)', calculation: `${burnoutRelated.toFixed(2)} preventable x 30% = ${attributed.toFixed(2)}/year avoided` },
        { step: 'Step 4: Cost Savings', calculation: `${attributed.toFixed(2)} avoided x $400,000 replacement cost = ${formatCurrency(driver.value)}` },
      ];
    } else if (name.includes('denial')) {
      const denials = Math.round(eligibleEncounters * 0.07);
      const docDenials = Math.round(denials * 0.35);
      const writtenOff = Math.round(docDenials * 0.30);
      const recovered = Math.round(writtenOff * 0.75);
      return [
        { step: 'Step 1: Total Denials', calculation: `${formatNumber(eligibleEncounters)} encounters x 7% denial rate = ${formatNumber(denials)} denials` },
        { step: 'Step 2: Documentation-Related (35%)', calculation: `${formatNumber(denials)} denials x 35% = ${formatNumber(docDenials)} doc denials` },
        { step: 'Step 3: Written Off (30%)', calculation: `${formatNumber(docDenials)} doc denials x 30% = ${formatNumber(writtenOff)} written off` },
        { step: 'Step 4: Abridge Recovery (75%)', calculation: `${formatNumber(writtenOff)} written off x 75% = ${formatNumber(recovered)} recovered` },
        { step: 'Step 5: Value', calculation: `${formatNumber(recovered)} claims x $250 avg value = ${formatCurrency(driver.value)}` },
      ];
    } else if (name.includes('overtime') || name.includes('locum')) {
      const allocatedHrs = Math.round(timeSavedHrs * 0.25);
      return [
        { step: 'Step 1: Time Saved', calculation: `${formatNumber(eligibleEncounters)} enc x ${timeSavedMin} min = ${formatNumber(Math.round(timeSavedHrs))} hours` },
        { step: 'Step 2: Overtime Reduction (25%)', calculation: `${formatNumber(Math.round(timeSavedHrs))} hrs x 25% = ${formatNumber(allocatedHrs)} hours` },
        { step: 'Step 3: Cost Savings', calculation: `${formatNumber(allocatedHrs)} hrs x $${hourlyRate}/hr = ${formatCurrency(driver.value)}` },
      ];
    }
    
    return [
      { step: 'Calculation', calculation: `Based on ${formatNumber(eligibleEncounters)} eligible encounters = ${formatCurrency(driver.value)}` },
    ];
  };
  
  for (let pageIdx = 0; pageIdx < driverPagesNeeded; pageIdx++) {
    doc.addPage();
    currentPage++;
    drawHeader();
    
    const startIdx = pageIdx * 2;
    const driversOnPage = allDrivers.slice(startIdx, startIdx + 2);
    
    driversOnPage.forEach((driver, idx) => {
      const driverNum = startIdx + idx + 1;
      const isLabor = data.laborDrivers.some(d => d.name === driver.name);
      const driverColor = isLabor ? COLORS.blue : COLORS.green;
      
      const startY = idx === 0 ? 28 : 145;
      let y = startY;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.mediumGray);
      doc.text(`VALUE DRIVER #${driverNum}`, margin, y);
      
      y += 5;
      drawBox(margin, y, contentWidth, 105, COLORS.white);
      
      // Driver header
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...driverColor);
      doc.text(driver.name.toUpperCase(), margin + 8, y + 10);
      doc.setTextColor(...COLORS.green);
      doc.text(formatCurrency(driver.value), pageWidth - margin - 8, y + 10, { align: 'right' });
      
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...COLORS.mediumGray);
      doc.text(driver.description || 'Value driver for ' + driver.name.toLowerCase(), margin + 8, y + 16);
      
      doc.setDrawColor(...COLORS.borderGray);
      doc.line(margin + 5, y + 20, pageWidth - margin - 5, y + 20);
      
      // THE THEORY
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.black);
      doc.text('THE THEORY', margin + 8, y + 28);
      
      drawBox(margin + 8, y + 30, contentWidth - 16, 18, COLORS.warmGray);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.darkGray);
      const theory = getDriverTheory(driver.name);
      const theoryLines = doc.splitTextToSize(theory, contentWidth - 24);
      doc.text(theoryLines.slice(0, 3), margin + 12, y + 36);
      
      // THE CALCULATION
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.black);
      doc.text('THE CALCULATION', margin + 8, y + 54);
      
      const steps = getDriverSteps(driver);
      let stepY = y + 60;
      steps.forEach((s) => {
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.darkGray);
        doc.text(s.step, margin + 10, stepY);
        doc.setFont('helvetica', 'normal');
        doc.text(s.calculation, margin + 55, stepY);
        stepY += 7;
      });
    });
    
    drawFooter();
  }
  
  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 5: INVESTMENT & THE JOURNEY
  // ═══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  currentPage++;
  drawHeader();
  
  yPos = 30;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR INVESTMENT', margin, yPos);
  
  yPos += 6;
  drawBox(margin, yPos, contentWidth, 65, COLORS.white);
  
  // Investment vs Value comparison bar - proportional widths
  const invBarY = yPos + 12;
  const invBarMaxWidth = (contentWidth - 30) / 2;
  const invMax = Math.max(data.investment, data.totalValue) || 1;
  const invPct = data.investment / invMax;
  const valPct = data.totalValue / invMax;
  
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('INVESTMENT', margin + 10, invBarY);
  doc.text('ANNUAL VALUE', margin + invBarMaxWidth + 20, invBarY);
  
  // Draw proportional bars
  drawBar(margin + 10, invBarY + 3, invBarMaxWidth, 8, invPct, COLORS.mediumGray, COLORS.subtleGray);
  drawBar(margin + invBarMaxWidth + 20, invBarY + 3, invBarMaxWidth, 8, valPct, COLORS.green, COLORS.subtleGray);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(formatCurrency(data.investment), margin + 10, invBarY + 20);
  doc.setTextColor(...COLORS.green);
  doc.text(formatCurrency(data.totalValue), margin + invBarMaxWidth + 20, invBarY + 20);
  
  // ROI callout box
  const roiBoxX = margin + 50;
  const roiBoxY = invBarY + 28;
  drawBox(roiBoxX, roiBoxY, contentWidth - 60, 25, COLORS.warmGray);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(`${data.roi.toFixed(1)}x ROI`, roiBoxX + (contentWidth - 60) / 2, roiBoxY + 10, { align: 'center' });
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Every $1 returns $${data.roi.toFixed(2)}`, roiBoxX + (contentWidth - 60) / 2, roiBoxY + 17, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text(`NET ANNUAL GAIN: ${formatCurrencyWithPlus(data.netGain)}`, roiBoxX + (contentWidth - 60) / 2, roiBoxY + 24, { align: 'center' });
  
  // YOUR CONFIGURATION
  yPos += 72;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR CONFIGURATION', margin, yPos);
  
  const configData = [
    [data.unitNamePlural, data.providers.toString()],
    ['Price', formatCurrency(data.costPerProvider) + '/' + data.unitName.toLowerCase() + '/month'],
    ['Annual Investment', formatCurrency(data.investment)],
  ];
  
  yPos += 3;
  autoTable(doc, {
    startY: yPos,
    body: configData,
    theme: 'plain',
    styles: { fontSize: 8, cellPadding: 2, textColor: COLORS.darkGray },
    columnStyles: { 0: { cellWidth: 50, fontStyle: 'bold' }, 1: { cellWidth: 50 } },
    tableWidth: 100,
    margin: { left: margin },
  });
  
  // YOUR JOURNEY WITH ABRIDGE
  yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR JOURNEY WITH ABRIDGE', margin, yPos);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Start with a pilot. Prove the value. Scale across your organization.', margin, yPos + 7);
  
  // Scaling journey visualization (simplified chart)
  yPos += 15;
  drawBox(margin, yPos, contentWidth, 50, COLORS.warmGray);
  
  // Draw simplified scaling line
  doc.setDrawColor(...COLORS.green);
  doc.setLineWidth(1);
  doc.line(margin + 20, yPos + 40, margin + contentWidth - 20, yPos + 15);
  
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Today', margin + 20, yPos + 46);
  doc.text(`${data.providers} ${data.unitNamePlural.toLowerCase()}`, margin + 20, yPos + 50);
  
  doc.text('Full Scale', margin + contentWidth - 35, yPos + 46);
  doc.text(`${data.fullScaleProviders} ${data.unitNamePlural.toLowerCase()}`, margin + contentWidth - 35, yPos + 50);
  
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.green);
  doc.text(formatCurrencyShort(data.totalValue), margin + 25, yPos + 35);
  doc.text(formatCurrencyShort(data.fullScaleValue), margin + contentWidth - 40, yPos + 12);
  
  // Pilot vs Full Scale cards
  yPos += 58;
  const halfWidth = (contentWidth - 10) / 2;
  
  drawBox(margin, yPos, halfWidth, 42, COLORS.white);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR STARTING POINT', margin + 5, yPos + 10);
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(`${data.providers} ${data.unitNamePlural.toLowerCase()}`, margin + 8, yPos + 18);
  doc.text(`${formatNumber(data.encounters)} encounters`, margin + 8, yPos + 24);
  doc.text(`${data.utilization}% utilization`, margin + 8, yPos + 30);
  doc.setTextColor(...COLORS.green);
  doc.text(`${formatCurrency(data.totalValue)}/year`, margin + 8, yPos + 36);
  
  drawBox(margin + halfWidth + 10, yPos, halfWidth, 42, COLORS.greenLight);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text('YOUR FULL SCALE POTENTIAL', margin + halfWidth + 15, yPos + 10);
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(`${data.fullScaleProviders} ${data.unitNamePlural.toLowerCase()}`, margin + halfWidth + 18, yPos + 18);
  doc.text(`${formatNumber(Math.round(data.encounters * (data.fullScaleProviders / data.providers)))} encounters`, margin + halfWidth + 18, yPos + 24);
  doc.text(`${data.fullScaleUtil}% utilization (at maturity)`, margin + halfWidth + 18, yPos + 30);
  doc.setTextColor(...COLORS.green);
  doc.text(`${formatCurrency(data.fullScaleValue)}/year`, margin + halfWidth + 18, yPos + 36);
  
  drawFooter();
  
  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 6: METHODOLOGY & ECONOMICS
  // ═══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  currentPage++;
  drawHeader();
  
  yPos = 30;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('THE ECONOMICS OF ADDING ' + data.unitNamePlural.toUpperCase(), margin, yPos);
  
  yPos += 6;
  drawBox(margin, yPos, contentWidth, 48, COLORS.white);
  
  // Per-provider metrics
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('ANNUAL BENEFIT PER ' + data.unitName.toUpperCase(), margin + 10, yPos + 10);
  
  const providerMetrics = [
    { value: formatCurrency(valuePerProvider), label: 'Gross Value', sublabel: 'per ' + data.unitName.toLowerCase() },
    { value: formatCurrency(netPerProvider), label: 'Net Benefit', sublabel: 'per ' + data.unitName.toLowerCase() },
    { value: formatCurrency(data.costPerProvider * 12), label: 'Investment', sublabel: 'per ' + data.unitName.toLowerCase() },
  ];
  
  const metricW = (contentWidth - 30) / 3;
  providerMetrics.forEach((m, i) => {
    const mx = margin + 10 + i * (metricW + 5);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...(i === 1 ? COLORS.green : COLORS.black));
    doc.text(m.value, mx + metricW / 2, yPos + 24, { align: 'center' });
    
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(m.label, mx + metricW / 2, yPos + 32, { align: 'center' });
    doc.text(m.sublabel, mx + metricW / 2, yPos + 38, { align: 'center' });
  });
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(`Every ${data.unitName.toLowerCase()} added generates ${formatCurrency(netPerProvider)} in net annual value.`, margin + 10, yPos + 46);
  
  // Multi-year projection
  yPos += 55;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('MULTI-YEAR PROJECTION', margin, yPos);
  
  const year2Val = Math.round(data.totalValue * 1.1);
  const year3Val = Math.round(data.totalValue * 1.21);
  const totalVal = data.totalValue + year2Val + year3Val;
  const totalCost = data.investment * 3;
  const totalNet = totalVal - totalCost;
  
  const projectionData = [
    ['', 'Year 1', 'Year 2', 'Year 3', '3-Yr Total'],
    ['Value', formatCurrencyShort(data.totalValue), formatCurrencyShort(year2Val), formatCurrencyShort(year3Val), formatCurrencyShort(totalVal)],
    ['Cost', formatCurrencyShort(data.investment), formatCurrencyShort(data.investment), formatCurrencyShort(data.investment), formatCurrencyShort(totalCost)],
    ['Net', formatCurrencyShort(data.netGain), formatCurrencyShort(year2Val - data.investment), formatCurrencyShort(year3Val - data.investment), formatCurrencyShort(totalNet)],
  ];
  
  yPos += 3;
  autoTable(doc, {
    startY: yPos,
    head: [projectionData[0]],
    body: projectionData.slice(1),
    theme: 'plain',
    styles: { fontSize: 8, cellPadding: 3, textColor: COLORS.darkGray, halign: 'center' },
    headStyles: { fillColor: COLORS.warmGray, fontStyle: 'bold', textColor: COLORS.black },
    columnStyles: { 0: { halign: 'left', fontStyle: 'bold' } },
    margin: { left: margin, right: margin },
    tableWidth: contentWidth,
  });
  
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Assumes 10% annual value growth with increased adoption', margin, (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5);
  
  // Methodology & Assumptions
  yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('METHODOLOGY & ASSUMPTIONS', margin, yPos);
  
  yPos += 5;
  
  // Two-column layout
  const colWidth = (contentWidth - 10) / 2;
  
  drawBox(margin, yPos, colWidth, 55, COLORS.warmGray);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR INPUTS', margin + 5, yPos + 10);
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  const inputs = [
    `${data.providers} ${data.unitNamePlural.toLowerCase()}`,
    `${formatNumber(data.encounters)} annual encounters`,
    `${data.utilization}% utilization`,
    `${formatCurrency(data.costPerProvider)}/${data.unitName.toLowerCase()}/month`,
  ];
  inputs.forEach((inp, i) => {
    doc.text('  ' + inp, margin + 8, yPos + 20 + i * 8);
  });
  
  drawBox(margin + colWidth + 10, yPos, colWidth, 55, COLORS.warmGray);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('ABRIDGE BENCHMARKS', margin + colWidth + 15, yPos + 10);
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  const benchmarks = [
    '65% typical utilization',
    '2.5 min saved per encounter',
    '5% wRVU improvement',
    '$33 Medicare conversion factor',
    '$400K replacement cost',
  ];
  benchmarks.forEach((bm, i) => {
    doc.text('  ' + bm, margin + colWidth + 18, yPos + 20 + i * 8);
  });
  
  // Valuation Assumptions
  yPos += 62;
  drawBox(margin, yPos, contentWidth, 42, COLORS.warmGray);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('VALUATION ASSUMPTIONS', margin + 5, yPos + 10);
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  const assumptions = [
    'Provider time: $150/hr (fully-loaded cost)',
    'Saved time allocation: 50% QoL, 25% access, 25% cost',
    'Visit conversion: 60% of allocated time becomes visits',
    'Retention: 30% attribution to documentation burden',
  ];
  assumptions.forEach((a, i) => {
    doc.text('  ' + a, margin + 8, yPos + 18 + i * 6);
  });
  
  // Closing quote
  yPos += 50;
  drawBox(margin, yPos, contentWidth, 28, COLORS.warmGray);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('"This isn\'t about whether ambient AI creates value. It does.', margin + 10, yPos + 10);
  doc.text('The question is whether you\'ll capture 40% of that value, or 85%."', margin + 10, yPos + 17);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text(`That choice is worth ${formatCurrency(data.netGain)} annually in ${data.setting.toLowerCase()} alone.`, margin + 10, yPos + 25);
  
  // Contact section
  yPos += 35;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.red);
  doc.text('ABRIDGE', margin, yPos);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Questions about this assessment?', margin, yPos + 8);
  doc.text('Contact your Abridge representative', margin, yPos + 14);
  
  drawFooter();
  
  // Save the PDF
  const filename = `Abridge_${data.setting}_ROI_Assessment_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
