import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface DriverDetail {
  id: string;
  name: string;
  value: number;
  category: 'labor' | 'revenue';
  theory: string;
  keyVariables?: { label: string; value: string }[];
  formula?: string;
  steps?: { label: string; calculation: string; result: string }[];
}

export interface PremiumPDFData {
  setting: string;
  unitName: string;
  unitNamePlural: string;
  providers: number;
  encounters: number;
  utilization: number;
  totalValue: number;
  investment: number;
  netGain: number;
  roi: number;
  costPerProvider: number;
  hoursReturned: number;
  additionalVisits: number;
  timeSaved: number;
  laborDrivers: { name: string; value: number; description: string }[];
  revenueDrivers: { name: string; value: number; description: string }[];
  laborTotal: number;
  revenueTotal: number;
  laborPct: number;
  revenuePct: number;
  year1: number;
  year2: number;
  year3: number;
  threeYearValue: number;
  threeYearCost: number;
  threeYearNet: number;
  fullScaleProviders: number;
  fullScaleUtil: number;
  fullScaleValue: number;
  fullScaleROI: number;
  networkEffect: number;
  qualitativeDrivers?: string[];
  driverDetails?: DriverDetail[];
}

const COLORS = {
  coral: [232, 90, 79] as [number, number, number],
  coralLight: [254, 242, 242] as [number, number, number],
  green: [5, 150, 105] as [number, number, number],
  greenLight: [236, 253, 245] as [number, number, number],
  black: [17, 24, 39] as [number, number, number],
  darkGray: [55, 65, 81] as [number, number, number],
  mediumGray: [107, 114, 128] as [number, number, number],
  lightGray: [156, 163, 175] as [number, number, number],
  backgroundGray: [249, 250, 251] as [number, number, number],
  borderGray: [229, 231, 235] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  capacityLabor: [59, 130, 246] as [number, number, number],
  revenueQuality: [16, 185, 129] as [number, number, number],
  abridgeRed: [234, 44, 0] as [number, number, number],
};

const formatNumber = (num: number): string => {
  if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
  if (num >= 1000) return Math.round(num / 1000).toLocaleString() + 'K';
  return Math.round(num).toLocaleString();
};

const formatCurrency = (num: number): string => {
  return '$' + formatNumber(num);
};

const formatCurrencyFull = (num: number): string => {
  return '$' + Math.round(num).toLocaleString();
};

export async function generatePremiumPDF(data: PremiumPDFData): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;
  let currentPage = 1;
  const totalPages = 6 + (data.laborDrivers.length + data.revenueDrivers.length);

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const drawHeader = () => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.abridgeRed);
    doc.text('ABRIDGE', margin, 15);
    
    doc.setTextColor(...COLORS.mediumGray);
    doc.setFont('helvetica', 'normal');
    doc.text('ROI Analysis', pageWidth - margin, 15, { align: 'right' });
    
    doc.setDrawColor(...COLORS.abridgeRed);
    doc.setLineWidth(0.5);
    doc.line(margin, 20, pageWidth - margin, 20);
  };

  const drawFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text('Generated by Abridge ROI Calculator', margin, pageHeight - 12);
    doc.text(`Page ${currentPage} of ${totalPages}`, pageWidth - margin, pageHeight - 12, { align: 'right' });
  };

  const drawSectionTitle = (title: string, y: number): number => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text(title.toUpperCase(), margin, y);
    return y + 12;
  };

  const drawCard = (x: number, y: number, w: number, h: number, fill: [number, number, number] = COLORS.backgroundGray) => {
    doc.setFillColor(...fill);
    doc.roundedRect(x, y, w, h, 2, 2, 'F');
  };

  // ==================== PAGE 1: COVER / EXECUTIVE SUMMARY ====================
  doc.setFillColor(...COLORS.white);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.abridgeRed);
  doc.text('ABRIDGE', margin, 35);
  
  doc.setDrawColor(...COLORS.abridgeRed);
  doc.setLineWidth(1);
  doc.line(margin, 45, pageWidth - margin, 45);
  
  yPos = 75;
  doc.setFontSize(28);
  doc.setTextColor(...COLORS.black);
  doc.text('ROI Analysis', margin, yPos);
  
  yPos += 12;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text(`${data.setting} Ambient Documentation`, margin, yPos);
  
  yPos += 20;
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(`Date: ${today}`, margin, yPos);
  
  doc.setDrawColor(...COLORS.borderGray);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos + 10, pageWidth - margin, yPos + 10);
  
  // YOUR ROI AT A GLANCE
  yPos += 25;
  yPos = drawSectionTitle('YOUR ROI AT A GLANCE', yPos);
  
  const heroCardWidth = (contentWidth - 10) / 2;
  const heroCardHeight = 50;
  
  drawCard(margin, yPos, heroCardWidth, heroCardHeight, COLORS.backgroundGray);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Net Annual Value', margin + 10, yPos + 12);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text('+' + formatCurrency(data.netGain), margin + 10, yPos + 30);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.lightGray);
  doc.text(`${formatCurrency(data.totalValue)} value - ${formatCurrency(data.investment)} investment`, margin + 10, yPos + 42);
  
  drawCard(margin + heroCardWidth + 10, yPos, heroCardWidth, heroCardHeight, COLORS.backgroundGray);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Return on Investment', margin + heroCardWidth + 20, yPos + 12);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text(data.roi.toFixed(1) + 'x', margin + heroCardWidth + 20, yPos + 30);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.lightGray);
  doc.text(`Every $1 invested returns $${data.roi.toFixed(2)}`, margin + heroCardWidth + 20, yPos + 42);
  
  // YOUR CONFIGURATION
  yPos += heroCardHeight + 20;
  yPos = drawSectionTitle('YOUR CONFIGURATION', yPos);
  
  const configBoxWidth = (contentWidth - 15) / 4;
  const configBoxHeight = 35;
  const configItems = [
    { value: data.providers.toString(), label: data.unitNamePlural },
    { value: formatNumber(data.encounters), label: 'Encounters' },
    { value: data.utilization + '%', label: 'Utilization' },
    { value: formatCurrency(data.investment), label: 'Investment' },
  ];
  
  configItems.forEach((item, i) => {
    const x = margin + i * (configBoxWidth + 5);
    doc.setDrawColor(...COLORS.borderGray);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, yPos, configBoxWidth, configBoxHeight, 2, 2, 'S');
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text(item.value, x + configBoxWidth / 2, yPos + 15, { align: 'center' });
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(item.label, x + configBoxWidth / 2, yPos + 26, { align: 'center' });
  });
  
  // VALUE BREAKDOWN
  yPos += configBoxHeight + 20;
  yPos = drawSectionTitle('VALUE BREAKDOWN', yPos);
  
  drawCard(margin, yPos, contentWidth, 70, COLORS.backgroundGray);
  
  let innerY = yPos + 10;
  
  if (data.laborDrivers.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.capacityLabor);
    doc.text('Capacity & Labor', margin + 8, innerY);
    doc.setTextColor(...COLORS.black);
    doc.text(formatCurrency(data.laborTotal), pageWidth - margin - 8, innerY, { align: 'right' });
    
    innerY += 8;
    data.laborDrivers.forEach((driver) => {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.darkGray);
      doc.text(driver.name, margin + 12, innerY);
      doc.text(formatCurrency(driver.value), pageWidth - margin - 12, innerY, { align: 'right' });
      innerY += 6;
    });
    innerY += 4;
  }
  
  if (data.revenueDrivers.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.revenueQuality);
    doc.text('Revenue & Quality', margin + 8, innerY);
    doc.setTextColor(...COLORS.black);
    doc.text(formatCurrency(data.revenueTotal), pageWidth - margin - 8, innerY, { align: 'right' });
    
    innerY += 8;
    data.revenueDrivers.forEach((driver) => {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.darkGray);
      doc.text(driver.name, margin + 12, innerY);
      doc.text(formatCurrency(driver.value), pageWidth - margin - 12, innerY, { align: 'right' });
      innerY += 6;
    });
  }
  
  // Divider and total
  const totalY = yPos + 55;
  doc.setDrawColor(...COLORS.borderGray);
  doc.line(margin + 8, totalY, pageWidth - margin - 8, totalY);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('Total Annual Value', margin + 8, totalY + 10);
  doc.text(formatCurrency(data.totalValue), pageWidth - margin - 8, totalY + 10, { align: 'right' });
  
  // Disclaimer
  yPos += 80;
  drawCard(margin, yPos, contentWidth, 28, COLORS.coralLight);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.darkGray);
  const disclaimerText = 'This analysis is based on your inputs and conservative assumptions. Actual results will vary based on implementation, adoption, and organizational factors. All calculations are detailed in the appendix for verification.';
  const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth - 16);
  doc.text(disclaimerLines, margin + 8, yPos + 10);
  
  drawFooter();
  
  // ==================== PAGE 2: UNDERSTANDING HOW AMBIENT AI CREATES VALUE ====================
  doc.addPage();
  currentPage = 2;
  drawHeader();
  yPos = 35;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('UNDERSTANDING HOW AMBIENT AI CREATES VALUE', margin, yPos);
  
  yPos += 15;
  drawCard(margin, yPos, contentWidth, 45, COLORS.backgroundGray);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  const introText = "Ambient AI doesn't create value directly - it returns time to clinicians and captures clinical information that would otherwise be lost. That time and information convert to value through specific, measurable pathways.\n\nThe value you realize depends on which pathways matter most to your organization and how well you optimize for them.";
  const introLines = doc.splitTextToSize(introText, contentWidth - 16);
  doc.text(introLines, margin + 8, yPos + 12);
  
  yPos += 55;
  yPos = drawSectionTitle('THE VALUE PATHWAYS', yPos);
  
  // Capacity & Labor pathway
  const pathwayHeight = 55;
  drawCard(margin, yPos, contentWidth, pathwayHeight, COLORS.white);
  doc.setDrawColor(...COLORS.capacityLabor);
  doc.setLineWidth(2);
  doc.line(margin, yPos, margin, yPos + pathwayHeight);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.capacityLabor);
  doc.text('CAPACITY & LABOR', margin + 8, yPos + 12);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Workforce efficiency and utilization', margin + 8, yPos + 20);
  
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.darkGray);
  const laborDesc = 'When clinicians spend less time on documentation, that time can convert to seeing more patients, reducing overtime, improving satisfaction, and reducing turnover.';
  const laborLines = doc.splitTextToSize(laborDesc, contentWidth - 20);
  doc.text(laborLines, margin + 8, yPos + 30);
  
  // Show selected labor drivers
  let driverX = margin + 8;
  const driverBoxW = 50;
  data.laborDrivers.forEach((driver) => {
    if (driverX + driverBoxW < pageWidth - margin) {
      doc.setFillColor(...COLORS.greenLight);
      doc.roundedRect(driverX, yPos + pathwayHeight - 15, driverBoxW, 12, 1, 1, 'F');
      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.green);
      doc.text('SELECTED', driverX + 2, yPos + pathwayHeight - 8);
      doc.setTextColor(...COLORS.black);
      doc.text(formatCurrency(driver.value), driverX + 28, yPos + pathwayHeight - 8);
      driverX += driverBoxW + 5;
    }
  });
  
  yPos += pathwayHeight + 10;
  
  // Revenue & Quality pathway
  drawCard(margin, yPos, contentWidth, pathwayHeight, COLORS.white);
  doc.setDrawColor(...COLORS.revenueQuality);
  doc.setLineWidth(2);
  doc.line(margin, yPos, margin, yPos + pathwayHeight);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.revenueQuality);
  doc.text('REVENUE & QUALITY', margin + 8, yPos + 12);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Clinical and financial accuracy', margin + 8, yPos + 20);
  
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.darkGray);
  const revenueDesc = 'When documentation captures the full clinical picture, organizations see improved coding accuracy, better HCC capture, and fewer documentation-related denials.';
  const revenueLines = doc.splitTextToSize(revenueDesc, contentWidth - 20);
  doc.text(revenueLines, margin + 8, yPos + 30);
  
  // Show selected revenue drivers
  driverX = margin + 8;
  data.revenueDrivers.forEach((driver) => {
    if (driverX + driverBoxW < pageWidth - margin) {
      doc.setFillColor(...COLORS.greenLight);
      doc.roundedRect(driverX, yPos + pathwayHeight - 15, driverBoxW, 12, 1, 1, 'F');
      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.green);
      doc.text('SELECTED', driverX + 2, yPos + pathwayHeight - 8);
      doc.setTextColor(...COLORS.black);
      doc.text(formatCurrency(driver.value), driverX + 28, yPos + pathwayHeight - 8);
      driverX += driverBoxW + 5;
    }
  });
  
  yPos += pathwayHeight + 20;
  
  // WHY CONSERVATIVE ASSUMPTIONS MATTER
  yPos = drawSectionTitle('WHY CONSERVATIVE ASSUMPTIONS MATTER', yPos);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('Every calculation in this analysis applies conservative factors:', margin, yPos);
  
  yPos += 10;
  const assumptions = [
    'Time conversion rates (15-33%) - Not all saved time converts to value',
    'Attribution factors (25-50%) - We only claim partial credit',
    'Audit haircuts (25%) - Accounts for revenue that doesn\'t survive review',
    'Utilization assumptions - Based on typical, not best-case, adoption',
  ];
  
  assumptions.forEach((assumption) => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.darkGray);
    doc.text('\u2022  ' + assumption, margin + 5, yPos);
    yPos += 7;
  });
  
  yPos += 5;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('These haircuts mean actual results could exceed these projections if adoption and implementation go well.', margin, yPos);
  
  drawFooter();
  
  // ==================== PAGE 3: YOUR SELECTED VALUE DRIVERS ====================
  doc.addPage();
  currentPage = 3;
  drawHeader();
  yPos = 35;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR SELECTED VALUE DRIVERS', margin, yPos);
  
  yPos += 10;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('These are the value pathways you\'ve chosen to model based on your strategic priorities.', margin, yPos);
  
  yPos += 15;
  
  const allDrivers = [...data.laborDrivers, ...data.revenueDrivers];
  const driverCardHeight = 48;
  
  allDrivers.forEach((driver, idx) => {
    if (yPos + driverCardHeight > pageHeight - 30) {
      drawFooter();
      doc.addPage();
      currentPage++;
      drawHeader();
      yPos = 35;
    }
    
    const isLabor = idx < data.laborDrivers.length;
    const categoryColor = isLabor ? COLORS.capacityLabor : COLORS.revenueQuality;
    
    drawCard(margin, yPos, contentWidth, driverCardHeight, COLORS.white);
    doc.setDrawColor(...COLORS.borderGray);
    doc.setLineWidth(0.3);
    doc.roundedRect(margin, yPos, contentWidth, driverCardHeight, 2, 2, 'S');
    
    // Driver name and value
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text(driver.name.toUpperCase(), margin + 8, yPos + 12);
    doc.setTextColor(...COLORS.green);
    doc.text(formatCurrency(driver.value), pageWidth - margin - 8, yPos + 12, { align: 'right' });
    
    doc.setDrawColor(...COLORS.borderGray);
    doc.line(margin + 8, yPos + 17, pageWidth - margin - 8, yPos + 17);
    
    // The Theory
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.darkGray);
    doc.text('The Theory', margin + 8, yPos + 25);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    const theoryText = driver.description || 'Reduces administrative burden and improves efficiency through AI-assisted documentation.';
    const theoryLines = doc.splitTextToSize(theoryText, contentWidth - 20);
    doc.text(theoryLines.slice(0, 2), margin + 8, yPos + 32);
    
    // Appendix reference
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(`Full calculation: See Appendix ${String.fromCharCode(65 + idx)}`, margin + 8, yPos + driverCardHeight - 5);
    
    yPos += driverCardHeight + 8;
  });
  
  drawFooter();
  
  // ==================== PAGE 4: THE SCALING OPPORTUNITY ====================
  doc.addPage();
  currentPage = 4;
  drawHeader();
  yPos = 35;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('THE SCALING OPPORTUNITY', margin, yPos);
  
  yPos += 10;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  const scalingIntro = `This analysis models your deployment of ${data.providers} ${data.unitNamePlural.toLowerCase()}. Here's what scaling to ${data.fullScaleProviders} ${data.unitNamePlural.toLowerCase()} could look like.`;
  doc.text(scalingIntro, margin, yPos);
  
  yPos += 18;
  
  // Pilot vs Full Scale comparison
  const comparisonWidth = (contentWidth - 10) / 2;
  const comparisonHeight = 70;
  
  // Pilot box
  drawCard(margin, yPos, comparisonWidth, comparisonHeight, COLORS.backgroundGray);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('PILOT (TODAY)', margin + comparisonWidth / 2, yPos + 12, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.black);
  doc.text(`${data.providers} ${data.unitNamePlural.toLowerCase()}`, margin + comparisonWidth / 2, yPos + 26, { align: 'center' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`${formatNumber(data.encounters)} encounters`, margin + comparisonWidth / 2, yPos + 35, { align: 'center' });
  doc.text(`${data.utilization}% utilization`, margin + comparisonWidth / 2, yPos + 43, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text(formatCurrency(data.totalValue), margin + comparisonWidth / 2, yPos + 56, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(`${data.roi.toFixed(1)}x ROI`, margin + comparisonWidth / 2, yPos + 64, { align: 'center' });
  
  // Full Scale box
  const fullScaleX = margin + comparisonWidth + 10;
  drawCard(fullScaleX, yPos, comparisonWidth, comparisonHeight, COLORS.greenLight);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text('FULL SCALE', fullScaleX + comparisonWidth / 2, yPos + 12, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.black);
  doc.text(`${data.fullScaleProviders} ${data.unitNamePlural.toLowerCase()}`, fullScaleX + comparisonWidth / 2, yPos + 26, { align: 'center' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const fullScaleEncounters = Math.round(data.encounters * (data.fullScaleProviders / data.providers));
  doc.text(`${formatNumber(fullScaleEncounters)} encounters`, fullScaleX + comparisonWidth / 2, yPos + 35, { align: 'center' });
  doc.text(`${data.fullScaleUtil}% utilization`, fullScaleX + comparisonWidth / 2, yPos + 43, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text(formatCurrency(data.fullScaleValue), fullScaleX + comparisonWidth / 2, yPos + 56, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(`${data.fullScaleROI.toFixed(1)}x ROI`, fullScaleX + comparisonWidth / 2, yPos + 64, { align: 'center' });
  
  yPos += comparisonHeight + 20;
  
  // THE COMPOUNDING EFFECT
  yPos = drawSectionTitle('THE COMPOUNDING EFFECT', yPos);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('The gap between linear projection and actual value represents compounding benefits:', margin, yPos);
  
  yPos += 12;
  const compoundingPoints = [
    `Utilization improves: ${data.utilization}% -> ${data.fullScaleUtil}% as adoption matures`,
    'Retention benefits materialize: Full impact after 6-12 months',
    'Efficiency compounds: Shared learnings, optimized workflows',
  ];
  
  compoundingPoints.forEach((point) => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.darkGray);
    doc.text('\u2022  ' + point, margin + 5, yPos);
    yPos += 8;
  });
  
  yPos += 10;
  
  // Compounding bonus card
  drawCard(margin, yPos, contentWidth, 35, COLORS.greenLight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text('COMPOUNDING BONUS', margin + 8, yPos + 12);
  
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.green);
  doc.text('+' + formatCurrency(data.networkEffect), margin + 8, yPos + 26);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('over 24 months beyond linear projection', margin + 80, yPos + 26);
  
  drawFooter();
  
  // ==================== PAGE 5: YOUR INVESTMENT ====================
  doc.addPage();
  currentPage = 5;
  drawHeader();
  yPos = 35;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR INVESTMENT', margin, yPos);
  
  yPos += 18;
  
  // Configuration and Multi-Year side by side
  const halfWidth = (contentWidth - 10) / 2;
  
  // Your Configuration
  drawCard(margin, yPos, halfWidth, 70, COLORS.backgroundGray);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('YOUR CONFIGURATION', margin + 8, yPos + 12);
  
  const configDetails = [
    ['Setting', data.setting],
    [data.unitNamePlural, String(data.providers)],
    ['Price', `$${data.costPerProvider}/mo`],
    ['Annual Investment', formatCurrency(data.investment)],
  ];
  
  let configY = yPos + 22;
  configDetails.forEach(([label, value]) => {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(label, margin + 8, configY);
    doc.setTextColor(...COLORS.black);
    doc.setFont('helvetica', 'bold');
    doc.text(value, margin + halfWidth - 8, configY, { align: 'right' });
    configY += 10;
  });
  
  // Multi-Year Projection
  const projectionX = margin + halfWidth + 10;
  drawCard(projectionX, yPos, halfWidth, 70, COLORS.backgroundGray);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('MULTI-YEAR PROJECTION', projectionX + 8, yPos + 12);
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Year 1', projectionX + 50, yPos + 22);
  doc.text('Year 2', projectionX + 70, yPos + 22);
  doc.text('Year 3', projectionX + 90, yPos + 22);
  
  const projY = yPos + 32;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Value', projectionX + 8, projY);
  doc.setTextColor(...COLORS.black);
  doc.text(formatCurrency(data.year1), projectionX + 50, projY);
  doc.text(formatCurrency(data.year2), projectionX + 70, projY);
  doc.text(formatCurrency(data.year3), projectionX + 90, projY);
  
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Cost', projectionX + 8, projY + 10);
  doc.setTextColor(...COLORS.black);
  doc.text(formatCurrency(data.investment), projectionX + 50, projY + 10);
  doc.text(formatCurrency(data.investment), projectionX + 70, projY + 10);
  doc.text(formatCurrency(data.investment), projectionX + 90, projY + 10);
  
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Net', projectionX + 8, projY + 20);
  doc.setTextColor(...COLORS.green);
  doc.text('+' + formatCurrency(data.year1 - data.investment), projectionX + 50, projY + 20);
  doc.text('+' + formatCurrency(data.year2 - data.investment), projectionX + 70, projY + 20);
  doc.text('+' + formatCurrency(data.year3 - data.investment), projectionX + 90, projY + 20);
  
  yPos += 85;
  
  // THE ROI EQUATION
  yPos = drawSectionTitle('THE ROI EQUATION', yPos);
  
  const eqBoxW = (contentWidth - 20) / 3;
  const eqBoxH = 35;
  
  // Value box
  drawCard(margin, yPos, eqBoxW, eqBoxH, COLORS.backgroundGray);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(formatCurrency(data.totalValue), margin + eqBoxW / 2, yPos + 15, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Value', margin + eqBoxW / 2, yPos + 26, { align: 'center' });
  
  // Minus sign
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.black);
  doc.text('-', margin + eqBoxW + 5, yPos + 18, { align: 'center' });
  
  // Investment box
  drawCard(margin + eqBoxW + 10, yPos, eqBoxW, eqBoxH, COLORS.backgroundGray);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text(formatCurrency(data.investment), margin + eqBoxW + 10 + eqBoxW / 2, yPos + 15, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Investment', margin + eqBoxW + 10 + eqBoxW / 2, yPos + 26, { align: 'center' });
  
  // Equals sign
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.black);
  doc.text('=', margin + 2 * eqBoxW + 15, yPos + 18, { align: 'center' });
  
  // Net Gain box
  drawCard(margin + 2 * eqBoxW + 20, yPos, eqBoxW, eqBoxH, COLORS.greenLight);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text('+' + formatCurrency(data.netGain), margin + 2 * eqBoxW + 20 + eqBoxW / 2, yPos + 15, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('Net Gain', margin + 2 * eqBoxW + 20 + eqBoxW / 2, yPos + 26, { align: 'center' });
  
  yPos += eqBoxH + 15;
  
  // ROI highlight box
  drawCard(margin + contentWidth / 2 - 35, yPos, 70, 35, COLORS.greenLight);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.green);
  doc.text(data.roi.toFixed(1) + 'x', margin + contentWidth / 2, yPos + 15, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.mediumGray);
  doc.text('ROI', margin + contentWidth / 2, yPos + 26, { align: 'center' });
  
  yPos += 50;
  
  // WHAT THIS MEANS
  yPos = drawSectionTitle('WHAT THIS MEANS', yPos);
  
  const paybackMonths = data.investment > 0 ? Math.round((data.investment / data.totalValue) * 12) : 0;
  const whatThisMeans = [
    `Your investment pays for itself in approximately ${paybackMonths} months`,
    `After month ${paybackMonths + 1}, every dollar is net positive value`,
    `Over 3 years, you could realize ${formatCurrency(data.threeYearNet)} in net value`,
    'These projections use conservative assumptions throughout',
  ];
  
  whatThisMeans.forEach((point) => {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.darkGray);
    doc.text('\u2022  ' + point, margin + 5, yPos);
    yPos += 8;
  });
  
  yPos += 10;
  drawCard(margin, yPos, contentWidth, 22, COLORS.backgroundGray);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('"The question isn\'t whether ambient AI creates value - it\'s whether your', margin + 8, yPos + 9);
  doc.text('organization is positioned to capture it."', margin + 8, yPos + 17);
  
  drawFooter();
  
  // ==================== PAGE 6: KEY ASSUMPTIONS & METHODOLOGY ====================
  doc.addPage();
  currentPage = 6;
  drawHeader();
  yPos = 35;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.black);
  doc.text('KEY ASSUMPTIONS & METHODOLOGY', margin, yPos);
  
  yPos += 10;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.darkGray);
  doc.text('This analysis is built on your inputs combined with industry benchmarks and conservative assumptions.', margin, yPos);
  
  yPos += 15;
  
  // YOUR INPUTS
  yPos = drawSectionTitle('YOUR INPUTS', yPos);
  
  const yourInputs = [
    `${data.providers} ${data.unitNamePlural.toLowerCase()} in scope`,
    `${formatNumber(data.encounters)} annual encounters`,
    `${data.utilization}% expected utilization`,
    `$${data.costPerProvider}/${data.unitName.toLowerCase()}/month pricing`,
    `${data.fullScaleProviders} total ${data.unitNamePlural.toLowerCase()} for scale scenario`,
    `${data.fullScaleUtil}% target utilization at full scale`,
  ];
  
  yourInputs.forEach((input) => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.darkGray);
    doc.text('\u2022  ' + input, margin + 5, yPos);
    yPos += 7;
  });
  
  yPos += 10;
  
  // CONSERVATIVE FACTORS APPLIED
  yPos = drawSectionTitle('CONSERVATIVE FACTORS APPLIED', yPos);
  
  const factorsData = [
    ['Factor', 'Rate', 'Why'],
    ['Time-to-access conversion', '25%', 'Not all time converts to visits'],
    ['Visit conversion rate', '60%', 'Scheduling/capacity constraints'],
    ['Burnout attribution', '30%', 'Conservative Abridge impact'],
    ['wRVU improvement', '5%', 'Validated benchmark'],
    ['HCC audit factor', '25%', 'Accounts for RADV and reviews'],
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [factorsData[0]],
    body: factorsData.slice(1),
    theme: 'plain',
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: COLORS.backgroundGray,
      textColor: COLORS.darkGray,
      fontStyle: 'bold',
      fontSize: 7,
    },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 20 },
      2: { cellWidth: 60 },
    },
    margin: { left: margin, right: margin },
  });
  
  yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  
  // INDUSTRY BENCHMARKS USED
  yPos = drawSectionTitle('INDUSTRY BENCHMARKS USED', yPos);
  
  const benchmarks = [
    'Physician replacement cost: $400,000-$800,000 (MGMA, AAFP)',
    'Physician turnover rate: 6-8% annually (AAMC)',
    'Burnout as departure factor: 40-50% (Mayo Clinic research)',
    'wRVU conversion factor: $33 (2024 Medicare)',
    'Average HCC value: $800 (CMS risk adjustment data)',
  ];
  
  benchmarks.forEach((benchmark) => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.darkGray);
    doc.text('\u2022  ' + benchmark, margin + 5, yPos);
    yPos += 7;
  });
  
  yPos += 10;
  
  // IMPORTANT NOTES
  yPos = drawSectionTitle('IMPORTANT NOTES', yPos);
  
  const notes = [
    'This analysis provides estimates for planning purposes',
    'Actual results will vary based on implementation and adoption',
    'Value realization requires organizational commitment',
    'Results compound over time with consistent usage',
    'All calculations detailed in appendix for verification',
  ];
  
  notes.forEach((note) => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.darkGray);
    doc.text('\u2022  ' + note, margin + 5, yPos);
    yPos += 7;
  });
  
  drawFooter();
  
  // ==================== APPENDIX PAGES - ONE PER DRIVER ====================
  const allDriversForAppendix = [...data.laborDrivers, ...data.revenueDrivers];
  
  allDriversForAppendix.forEach((driver, idx) => {
    doc.addPage();
    currentPage++;
    drawHeader();
    yPos = 35;
    
    const appendixLetter = String.fromCharCode(65 + idx);
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text(`APPENDIX ${appendixLetter}: ${driver.name.toUpperCase()} CALCULATION`, margin, yPos);
    
    yPos += 18;
    
    // The Theory box
    drawCard(margin, yPos, contentWidth, 40, COLORS.backgroundGray);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text('THE THEORY', margin + 8, yPos + 12);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.darkGray);
    const theoryText = driver.description || 'When documentation burden is reduced, organizations see measurable improvements in efficiency and value creation.';
    const theoryLines = doc.splitTextToSize(theoryText, contentWidth - 16);
    doc.text(theoryLines, margin + 8, yPos + 22);
    
    yPos += 50;
    
    // Calculation steps
    yPos = drawSectionTitle('STEP-BY-STEP CALCULATION', yPos);
    
    // Step 1: Base calculation
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text('Step 1: Establish baseline', margin, yPos);
    
    yPos += 10;
    drawCard(margin, yPos, contentWidth, 25, COLORS.white);
    doc.setDrawColor(...COLORS.borderGray);
    doc.roundedRect(margin, yPos, contentWidth, 25, 2, 2, 'S');
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.darkGray);
    doc.text(`${data.encounters} encounters x ${data.utilization}% utilization = ${formatNumber(Math.round(data.encounters * data.utilization / 100))} eligible encounters`, margin + 8, yPos + 10);
    doc.text(`${data.providers} ${data.unitNamePlural.toLowerCase()} in scope`, margin + 8, yPos + 18);
    
    yPos += 35;
    
    // Step 2: Apply factors
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text('Step 2: Apply conservative factors', margin, yPos);
    
    yPos += 10;
    drawCard(margin, yPos, contentWidth, 25, COLORS.white);
    doc.setDrawColor(...COLORS.borderGray);
    doc.roundedRect(margin, yPos, contentWidth, 25, 2, 2, 'S');
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.darkGray);
    doc.text('Conservative factors applied to ensure defensible projections', margin + 8, yPos + 10);
    doc.text('Attribution factors, conversion rates, and audit haircuts included', margin + 8, yPos + 18);
    
    yPos += 35;
    
    // Step 3: Final value
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.black);
    doc.text('Step 3: Calculate final value', margin, yPos);
    
    yPos += 10;
    drawCard(margin, yPos, contentWidth, 30, COLORS.greenLight);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.green);
    doc.text(`Annual Value: ${formatCurrencyFull(driver.value)}`, margin + 8, yPos + 12);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.darkGray);
    doc.text('This represents the conservative annual value contribution from this driver.', margin + 8, yPos + 22);
    
    yPos += 45;
    
    // Key assumptions for this driver
    yPos = drawSectionTitle('KEY ASSUMPTIONS FOR THIS DRIVER', yPos);
    
    const driverAssumptions = [
      'Values based on industry benchmarks and Abridge customer data',
      'Conservative attribution factors applied',
      'Assumes consistent utilization throughout the period',
      'Does not account for potential compounding effects',
    ];
    
    driverAssumptions.forEach((assumption) => {
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.darkGray);
      doc.text('\u2022  ' + assumption, margin + 5, yPos);
      yPos += 7;
    });
    
    drawFooter();
  });
  
  // Save the PDF
  const filename = `Abridge_ROI_${data.setting.replace(/\s+/g, '_')}_${data.providers}P.pdf`;
  doc.save(filename);
}
