export const DS = {
  bg: '#FAFAF9',
  black: '#0F0F0F',
  body: '#525252',
  muted: '#A3A3A3',
  border: '#EDEDED',
  red: '#EA2C00',
  redHover: '#C72300',
  redActive: '#A81F00',
  white: '#FFFFFF',
  hoverBg: '#F5F5F4',
  maxWidth: 600,
  font: 'Manrope, sans-serif',
  radius: { card: 14, input: 10, pill: 999 },
  shadow: '0 1px 3px rgba(0,0,0,0.06)',
} as const;

export const fontStyles = {
  display: (mobile = false): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 700,
    fontSize: mobile ? 38 : 52,
    color: DS.black,
    lineHeight: 1.15,
  }),
  title: (mobile = false): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 600,
    fontSize: mobile ? 20 : 24,
    color: DS.black,
    lineHeight: 1.3,
  }),
  body: (): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 400,
    fontSize: 17,
    color: DS.body,
    lineHeight: 1.75,
  }),
  label: (): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 600,
    fontSize: 11,
    color: DS.muted,
    letterSpacing: '2.5px',
    textTransform: 'uppercase' as const,
  }),
  dataLarge: (): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 700,
    fontSize: 72,
    color: DS.black,
    lineHeight: 1,
  }),
  dataMedium: (color = DS.black): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 700,
    fontSize: 36,
    color,
    lineHeight: 1,
  }),
  dataSmall: (): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 600,
    fontSize: 20,
    color: DS.black,
    lineHeight: 1.3,
  }),
  footnote: (): React.CSSProperties => ({
    fontFamily: DS.font,
    fontWeight: 400,
    fontSize: 13,
    color: DS.muted,
    lineHeight: 1.6,
  }),
} as const;
